//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources.View.ExchangeRate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.View.ExchangeRate.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Exchange Rate.
        /// </summary>
        public static string ChangeTitle {
            get {
                return ResourceManager.GetString("ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY NAME.
        /// </summary>
        public static string CURNAME {
            get {
                return ResourceManager.GetString("CURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert ExchangRate.
        /// </summary>
        public static string InsertTitle {
            get {
                return ResourceManager.GetString("InsertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a number..
        /// </summary>
        public static string IsNumber {
            get {
                return ResourceManager.GetString("IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Master.
        /// </summary>
        public static string MasterTitle {
            get {
                return ResourceManager.GetString("MasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {0} characters..
        /// </summary>
        public static string Maxlength {
            get {
                return ResourceManager.GetString("Maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no less than {0} characters..
        /// </summary>
        public static string Minlength {
            get {
                return ResourceManager.GetString("Minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY CODE.
        /// </summary>
        public static string MJCRRCD {
            get {
                return ResourceManager.GetString("MJCRRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string MJEXRDT {
            get {
                return ResourceManager.GetString("MJEXRDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCHANGE RATE.
        /// </summary>
        public static string MJEXRT {
            get {
                return ResourceManager.GetString("MJEXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCHANGE RATE TYPE.
        /// </summary>
        public static string MJEXRTT {
            get {
                return ResourceManager.GetString("MJEXRTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER DATE.
        /// </summary>
        public static string MJRGSDT {
            get {
                return ResourceManager.GetString("MJRGSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER TIME.
        /// </summary>
        public static string MJRGSTM {
            get {
                return ResourceManager.GetString("MJRGSTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXCHANGE RATE (TAX).
        /// </summary>
        public static string MJTXEXR {
            get {
                return ResourceManager.GetString("MJTXEXR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF UPDATE.
        /// </summary>
        public static string MJUPDT {
            get {
                return ResourceManager.GetString("MJUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME OF UPDATE.
        /// </summary>
        public static string MJUPDTM {
            get {
                return ResourceManager.GetString("MJUPDTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Currency Code.
        /// </summary>
        public static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code already in used.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter this feild.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select row to delete !.
        /// </summary>
        public static string SelectRow {
            get {
                return ResourceManager.GetString("SelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data valid must have format MM/YYYY.
        /// </summary>
        public static string ValidDate {
            get {
                return ResourceManager.GetString("ValidDate", resourceCulture);
            }
        }
    }
}
