//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources.View.PUR001 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.View.PUR001.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collation No.
        /// </summary>
        public static string AACLLNO {
            get {
                return ResourceManager.GetString("AACLLNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity .
        /// </summary>
        public static string AACMDCD {
            get {
                return ResourceManager.GetString("AACMDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Status.
        /// </summary>
        public static string AACMPCD {
            get {
                return ResourceManager.GetString("AACMPCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        public static string AACMPDT {
            get {
                return ResourceManager.GetString("AACMPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string AACRRCD {
            get {
                return ResourceManager.GetString("AACRRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No.
        /// </summary>
        public static string AACTITM {
            get {
                return ResourceManager.GetString("AACTITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string AACTRTP {
            get {
                return ResourceManager.GetString("AACTRTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge &amp; Loading Port.
        /// </summary>
        public static string AADLPOT {
            get {
                return ResourceManager.GetString("AADLPOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Condition.
        /// </summary>
        public static string AADLVCD {
            get {
                return ResourceManager.GetString("AADLVCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit/Asset.
        /// </summary>
        public static string AADPSCD {
            get {
                return ResourceManager.GetString("AADPSCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AADSTNC {
            get {
                return ResourceManager.GetString("AADSTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Code.
        /// </summary>
        public static string AADTCD {
            get {
                return ResourceManager.GetString("AADTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string AAEXRT {
            get {
                return ResourceManager.GetString("AAEXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Type.
        /// </summary>
        public static string AAEXRTT {
            get {
                return ResourceManager.GetString("AAEXRTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Incharge.
        /// </summary>
        public static string AAIDCD {
            get {
                return ResourceManager.GetString("AAIDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker Code.
        /// </summary>
        public static string AAMKCD {
            get {
                return ResourceManager.GetString("AAMKCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Term.
        /// </summary>
        public static string AAPRICE {
            get {
                return ResourceManager.GetString("AAPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Terms.
        /// </summary>
        public static string AAPTTRM {
            get {
                return ResourceManager.GetString("AAPTTRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Contract No.
        /// </summary>
        public static string AAPURNO {
            get {
                return ResourceManager.GetString("AAPURNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string AARGSDT {
            get {
                return ResourceManager.GetString("AARGSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark1.
        /// </summary>
        public static string AARMK1 {
            get {
                return ResourceManager.GetString("AARMK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark2 .
        /// </summary>
        public static string AARMK2 {
            get {
                return ResourceManager.GetString("AARMK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark3.
        /// </summary>
        public static string AARMK3 {
            get {
                return ResourceManager.GetString("AARMK3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark4.
        /// </summary>
        public static string AARMK4 {
            get {
                return ResourceManager.GetString("AARMK4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark5.
        /// </summary>
        public static string AARMK5 {
            get {
                return ResourceManager.GetString("AARMK5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RawMaterial Type.
        /// </summary>
        public static string AARMTP {
            get {
                return ResourceManager.GetString("AARMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Incharge.
        /// </summary>
        public static string AASCTNC {
            get {
                return ResourceManager.GetString("AASCTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Term.
        /// </summary>
        public static string AASETRM {
            get {
                return ResourceManager.GetString("AASETRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Month.
        /// </summary>
        public static string AASHPDT {
            get {
                return ResourceManager.GetString("AASHPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code.
        /// </summary>
        public static string AASPLCD {
            get {
                return ResourceManager.GetString("AASPLCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Contract No.
        /// </summary>
        public static string AASPPNO {
            get {
                return ResourceManager.GetString("AASPPNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support/Long Term.
        /// </summary>
        public static string AASPTCD {
            get {
                return ResourceManager.GetString("AASPTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Company No.
        /// </summary>
        public static string AATCNO {
            get {
                return ResourceManager.GetString("AATCNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Type(Tax).
        /// </summary>
        public static string AATEXRT {
            get {
                return ResourceManager.GetString("AATEXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Category.
        /// </summary>
        public static string AATRDCD {
            get {
                return ResourceManager.GetString("AATRDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        public static string AATXCD {
            get {
                return ResourceManager.GetString("AATXCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate(Tax).
        /// </summary>
        public static string AATXEXR {
            get {
                return ResourceManager.GetString("AATXEXR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        public static string AATXRT {
            get {
                return ResourceManager.GetString("AATXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string AAUPDT {
            get {
                return ResourceManager.GetString("AAUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management No.
        /// </summary>
        public static string AAUSMSG {
            get {
                return ResourceManager.GetString("AAUSMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code.
        /// </summary>
        public static string AAUSRCD {
            get {
                return ResourceManager.GetString("AAUSRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size(Length).
        /// </summary>
        public static string ABBSZL {
            get {
                return ResourceManager.GetString("ABBSZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size(Thk).
        /// </summary>
        public static string ABBSZT {
            get {
                return ResourceManager.GetString("ABBSZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size(Width).
        /// </summary>
        public static string ABBSZW {
            get {
                return ResourceManager.GetString("ABBSZW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compination (Length).
        /// </summary>
        public static string ABCMBL {
            get {
                return ResourceManager.GetString("ABCMBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compination (Thk).
        /// </summary>
        public static string ABCMBT {
            get {
                return ResourceManager.GetString("ABCMBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compination (Width).
        /// </summary>
        public static string ABCMBW {
            get {
                return ResourceManager.GetString("ABCMBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating.
        /// </summary>
        public static string ABCOAT {
            get {
                return ResourceManager.GetString("ABCOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No.
        /// </summary>
        public static string ABCTITM {
            get {
                return ResourceManager.GetString("ABCTITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string ABDLVDT {
            get {
                return ResourceManager.GetString("ABDLVDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinction.
        /// </summary>
        public static string ABDSTNC {
            get {
                return ResourceManager.GetString("ABDSTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Code.
        /// </summary>
        public static string ABDTCD {
            get {
                return ResourceManager.GetString("ABDTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string ABGRADE {
            get {
                return ResourceManager.GetString("ABGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Coil Spec.
        /// </summary>
        public static string ABMCSPC {
            get {
                return ResourceManager.GetString("ABMCSPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No.
        /// </summary>
        public static string ABORDNO {
            get {
                return ResourceManager.GetString("ABORDNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Amt.
        /// </summary>
        public static string ABPRAT {
            get {
                return ResourceManager.GetString("ABPRAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pruchase Amt(Dcurr).
        /// </summary>
        public static string ABPRATD {
            get {
                return ResourceManager.GetString("ABPRATD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Diameter.
        /// </summary>
        public static string ABPRDDIA {
            get {
                return ResourceManager.GetString("ABPRDDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ABPRDNM {
            get {
                return ResourceManager.GetString("ABPRDNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase U/P.
        /// </summary>
        public static string ABPRUP {
            get {
                return ResourceManager.GetString("ABPRUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase U/P(Dcurr).
        /// </summary>
        public static string ABPRUPD {
            get {
                return ResourceManager.GetString("ABPRUPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase U.P/U.
        /// </summary>
        public static string ABPRUPU {
            get {
                return ResourceManager.GetString("ABPRUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prchs Tax Amt(Dcurr).
        /// </summary>
        public static string ABPTXAD {
            get {
                return ResourceManager.GetString("ABPTXAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Tax Amt.
        /// </summary>
        public static string ABPTXAT {
            get {
                return ResourceManager.GetString("ABPTXAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Contract No.
        /// </summary>
        public static string ABPURNO {
            get {
                return ResourceManager.GetString("ABPURNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ABQTY {
            get {
                return ResourceManager.GetString("ABQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string ABRGSDT {
            get {
                return ResourceManager.GetString("ABRGSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stockentry Date.
        /// </summary>
        public static string ABSEDT {
            get {
                return ResourceManager.GetString("ABSEDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stck Entry Sch Wt.
        /// </summary>
        public static string ABSESWT {
            get {
                return ResourceManager.GetString("ABSESWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size(Length).
        /// </summary>
        public static string ABSIZEL {
            get {
                return ResourceManager.GetString("ABSIZEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size(Thk).
        /// </summary>
        public static string ABSIZET {
            get {
                return ResourceManager.GetString("ABSIZET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size(Width).
        /// </summary>
        public static string ABSIZEW {
            get {
                return ResourceManager.GetString("ABSIZEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ttl-Wt Of Stck Entry.
        /// </summary>
        public static string ABTTLWT {
            get {
                return ResourceManager.GetString("ABTTLWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Update.
        /// </summary>
        public static string ABUPDT {
            get {
                return ResourceManager.GetString("ABUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string ABWT {
            get {
                return ResourceManager.GetString("ABWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete sucessfull..
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete fail, please try later..
        /// </summary>
        public static string CompleteFail {
            get {
                return ResourceManager.GetString("CompleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is empty..
        /// </summary>
        public static string DataEmpty {
            get {
                return ResourceManager.GetString("DataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must have format MM/yyyy.
        /// </summary>
        public static string DateFormatMMflagyyyy {
            get {
                return ResourceManager.GetString("DateFormatMMflagyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export fail..
        /// </summary>
        public static string ExportFileFail {
            get {
                return ResourceManager.GetString("ExportFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successfull..
        /// </summary>
        public static string ExportFileSuccess {
            get {
                return ResourceManager.GetString("ExportFileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Sp Contract No.
        /// </summary>
        public static string PlaceholderTextSearch {
            get {
                return ResourceManager.GetString("PlaceholderTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steal Grade.
        /// </summary>
        public static string RAPSTLGR {
            get {
                return ResourceManager.GetString("RAPSTLGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ? Contract cannot edit or restore after completed..
        /// </summary>
        public static string WarningCompleteAllSelect {
            get {
                return ResourceManager.GetString("WarningCompleteAllSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select currency code..
        /// </summary>
        public static string WarningSelectCurrencyCode {
            get {
                return ResourceManager.GetString("WarningSelectCurrencyCode", resourceCulture);
            }
        }
    }
}
