//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources.View.TRA001 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.View.TRA001.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment No.
        /// </summary>
        public static string DAADJNO {
            get {
                return ResourceManager.GetString("DAADJNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Weigth.
        /// </summary>
        public static string DABALWT {
            get {
                return ResourceManager.GetString("DABALWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Code.
        /// </summary>
        public static string DABKCD {
            get {
                return ResourceManager.GetString("DABKCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookingb Timing.
        /// </summary>
        public static string DABKTMG {
            get {
                return ResourceManager.GetString("DABKTMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Site(Length).
        /// </summary>
        public static string DABSZL {
            get {
                return ResourceManager.GetString("DABSZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Site(Thk).
        /// </summary>
        public static string DABSZT {
            get {
                return ResourceManager.GetString("DABSZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Site(Width).
        /// </summary>
        public static string DABSZW {
            get {
                return ResourceManager.GetString("DABSZW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Weight.
        /// </summary>
        public static string DACALWT {
            get {
                return ResourceManager.GetString("DACALWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incharge Of Work.
        /// </summary>
        public static string DACHGWK {
            get {
                return ResourceManager.GetString("DACHGWK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comodity Code.
        /// </summary>
        public static string DACMDCD {
            get {
                return ResourceManager.GetString("DACMDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating.
        /// </summary>
        public static string DACOAT {
            get {
                return ResourceManager.GetString("DACOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string DACSTCD {
            get {
                return ResourceManager.GetString("DACSTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Hndl Chagre.
        /// </summary>
        public static string DACSTHC {
            get {
                return ResourceManager.GetString("DACSTHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string DACTINF {
            get {
                return ResourceManager.GetString("DACTINF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No Of P-Cnt No.
        /// </summary>
        public static string DACTITM {
            get {
                return ResourceManager.GetString("DACTITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cstm Hndl Chrg Pd To.
        /// </summary>
        public static string DACTPDT {
            get {
                return ResourceManager.GetString("DACTPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Contract No.
        /// </summary>
        public static string DACTRNO {
            get {
                return ResourceManager.GetString("DACTRNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string DACTRTP {
            get {
                return ResourceManager.GetString("DACTRTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Spec.
        /// </summary>
        public static string DACTSPC {
            get {
                return ResourceManager.GetString("DACTSPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cstm Hndl Chrg U/P.
        /// </summary>
        public static string DACTUP {
            get {
                return ResourceManager.GetString("DACTUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cstm Hndl Chrg U.P/U.
        /// </summary>
        public static string DACTUPU {
            get {
                return ResourceManager.GetString("DACTUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deficit/Surplus.
        /// </summary>
        public static string DADFTSR {
            get {
                return ResourceManager.GetString("DADFTSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/I No.
        /// </summary>
        public static string DADINO {
            get {
                return ResourceManager.GetString("DADINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date To User.
        /// </summary>
        public static string DADLDTT {
            get {
                return ResourceManager.GetString("DADLDTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery To.
        /// </summary>
        public static string DADLVTO {
            get {
                return ResourceManager.GetString("DADLVTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/O No.
        /// </summary>
        public static string DADONO {
            get {
                return ResourceManager.GetString("DADONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub No Of D/O No.
        /// </summary>
        public static string DADOSUB {
            get {
                return ResourceManager.GetString("DADOSUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit/Asset Code.
        /// </summary>
        public static string DADPSCD {
            get {
                return ResourceManager.GetString("DADPSCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DADSTNC {
            get {
                return ResourceManager.GetString("DADSTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string DAEXRT {
            get {
                return ResourceManager.GetString("DAEXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Type.
        /// </summary>
        public static string DAEXRTT {
            get {
                return ResourceManager.GetString("DAEXRTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frt Hndl Chrg Pd To.
        /// </summary>
        public static string DAFHPDT {
            get {
                return ResourceManager.GetString("DAFHPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Paid To.
        /// </summary>
        public static string DAFRPDT {
            get {
                return ResourceManager.GetString("DAFRPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Unit Price.
        /// </summary>
        public static string DAFRTUP {
            get {
                return ResourceManager.GetString("DAFRTUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight U.P/U.
        /// </summary>
        public static string DAFRUPU {
            get {
                return ResourceManager.GetString("DAFRUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string DAGRADE {
            get {
                return ResourceManager.GetString("DAGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hndl Chgr Amount.
        /// </summary>
        public static string DAHCGAT {
            get {
                return ResourceManager.GetString("DAHCGAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Code.
        /// </summary>
        public static string DAIDCD {
            get {
                return ResourceManager.GetString("DAIDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity In A Pck.
        /// </summary>
        public static string DAINPCK {
            get {
                return ResourceManager.GetString("DAINPCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prc Chrg Amt(Int Rnl).
        /// </summary>
        public static string DAINTPC {
            get {
                return ResourceManager.GetString("DAINTPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prc Chrg Amt(Intrnl).
        /// </summary>
        public static string DAINTPK {
            get {
                return ResourceManager.GetString("DAINTPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventory No.
        /// </summary>
        public static string DAINVNO {
            get {
                return ResourceManager.GetString("DAINVNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventory Type.
        /// </summary>
        public static string DAINVTP {
            get {
                return ResourceManager.GetString("DAINVTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itm No (Orgnl Pur Slp).
        /// </summary>
        public static string DAIOPSL {
            get {
                return ResourceManager.GetString("DAIOPSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itm No(Orginal Slip ).
        /// </summary>
        public static string DAIOSSL {
            get {
                return ResourceManager.GetString("DAIOSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection No.
        /// </summary>
        public static string DAISPNO {
            get {
                return ResourceManager.GetString("DAISPNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No (Sale Slip).
        /// </summary>
        public static string DAISSLP {
            get {
                return ResourceManager.GetString("DAISSLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string DAIVCDT {
            get {
                return ResourceManager.GetString("DAIVCDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No Of Job No.
        /// </summary>
        public static string DAJBITM {
            get {
                return ResourceManager.GetString("DAJBITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job No.
        /// </summary>
        public static string DAJOBNO {
            get {
                return ResourceManager.GetString("DAJOBNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Code.
        /// </summary>
        public static string DALCTCD {
            get {
                return ResourceManager.GetString("DALCTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Date.
        /// </summary>
        public static string DALOGDT {
            get {
                return ResourceManager.GetString("DALOGDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type.
        /// </summary>
        public static string DALOGTP {
            get {
                return ResourceManager.GetString("DALOGTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine No.
        /// </summary>
        public static string DAMCHNO {
            get {
                return ResourceManager.GetString("DAMCHNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Code.
        /// </summary>
        public static string DAMKCD {
            get {
                return ResourceManager.GetString("DAMKCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The No Of Revision.
        /// </summary>
        public static string DANORVS {
            get {
                return ResourceManager.GetString("DANORVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Entry Date.
        /// </summary>
        public static string DAOEDT {
            get {
                return ResourceManager.GetString("DAOEDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No (O.E No).
        /// </summary>
        public static string DAOEITM {
            get {
                return ResourceManager.GetString("DAOEITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Entry No.
        /// </summary>
        public static string DAOENO {
            get {
                return ResourceManager.GetString("DAOENO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original No.
        /// </summary>
        public static string DAOGLNO {
            get {
                return ResourceManager.GetString("DAOGLNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orgnl Prchs Slip No.
        /// </summary>
        public static string DAOPSLP {
            get {
                return ResourceManager.GetString("DAOPSLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No.
        /// </summary>
        public static string DAORDNO {
            get {
                return ResourceManager.GetString("DAORDNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orginal Sale Slip No.
        /// </summary>
        public static string DAOSSLP {
            get {
                return ResourceManager.GetString("DAOSSLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paking Date.
        /// </summary>
        public static string DAPCKDT {
            get {
                return ResourceManager.GetString("DAPCKDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paking Mark.
        /// </summary>
        public static string DAPCKM {
            get {
                return ResourceManager.GetString("DAPCKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paking No.
        /// </summary>
        public static string DAPCKNO {
            get {
                return ResourceManager.GetString("DAPCKNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paking Type.
        /// </summary>
        public static string DAPCKTP {
            get {
                return ResourceManager.GetString("DAPCKTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prch Frght U/P.
        /// </summary>
        public static string DAPFRUP {
            get {
                return ResourceManager.GetString("DAPFRUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prch Frght U.P/U.
        /// </summary>
        public static string DAPFUPU {
            get {
                return ResourceManager.GetString("DAPFUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Id.
        /// </summary>
        public static string DAPGMID {
            get {
                return ResourceManager.GetString("DAPGMID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Invoice Date.
        /// </summary>
        public static string DAPIVDT {
            get {
                return ResourceManager.GetString("DAPIVDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Invoice No.
        /// </summary>
        public static string DAPIVNO {
            get {
                return ResourceManager.GetString("DAPIVNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prc Chrg Amt(Subcnt).
        /// </summary>
        public static string DAPKATB {
            get {
                return ResourceManager.GetString("DAPKATB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O. No.
        /// </summary>
        public static string DAPONO {
            get {
                return ResourceManager.GetString("DAPONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prc Chrg Amt(Subcnt).
        /// </summary>
        public static string DAPRATB {
            get {
                return ResourceManager.GetString("DAPRATB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Date.
        /// </summary>
        public static string DAPRCDT {
            get {
                return ResourceManager.GetString("DAPRCDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Type.
        /// </summary>
        public static string DAPRCTP {
            get {
                return ResourceManager.GetString("DAPRCTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string DAPRDNM {
            get {
                return ResourceManager.GetString("DAPRDNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Slip No.
        /// </summary>
        public static string DAPSLP {
            get {
                return ResourceManager.GetString("DAPSLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itm No (Prchs Slip No).
        /// </summary>
        public static string DAPSLPI {
            get {
                return ResourceManager.GetString("DAPSLPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prchcs Frt Amount.
        /// </summary>
        public static string DAPUFAT {
            get {
                return ResourceManager.GetString("DAPUFAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Freight To.
        /// </summary>
        public static string DAPUFRT {
            get {
                return ResourceManager.GetString("DAPUFRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Amount.
        /// </summary>
        public static string DAPURAT {
            get {
                return ResourceManager.GetString("DAPURAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Goods Code.
        /// </summary>
        public static string DAPURGD {
            get {
                return ResourceManager.GetString("DAPURGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Unit Price.
        /// </summary>
        public static string DAPURUP {
            get {
                return ResourceManager.GetString("DAPURUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase U.P/U.
        /// </summary>
        public static string DAPUUPU {
            get {
                return ResourceManager.GetString("DAPUUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string DAQTY {
            get {
                return ResourceManager.GetString("DAQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string DARMK20 {
            get {
                return ResourceManager.GetString("DARMK20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Code.
        /// </summary>
        public static string DARSNCD {
            get {
                return ResourceManager.GetString("DARSNCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Incharge.
        /// </summary>
        public static string DASCTNC {
            get {
                return ResourceManager.GetString("DASCTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Code.
        /// </summary>
        public static string DASECCD {
            get {
                return ResourceManager.GetString("DASECCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Entry Date.
        /// </summary>
        public static string DASEDT {
            get {
                return ResourceManager.GetString("DASEDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Code.
        /// </summary>
        public static string DASHIFT {
            get {
                return ResourceManager.GetString("DASHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale U/P.
        /// </summary>
        public static string DASLUP {
            get {
                return ResourceManager.GetString("DASLUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale U.P/U.
        /// </summary>
        public static string DASLUPU {
            get {
                return ResourceManager.GetString("DASLUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Month.
        /// </summary>
        public static string DASMNTH {
            get {
                return ResourceManager.GetString("DASMNTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec.
        /// </summary>
        public static string DASPEC {
            get {
                return ResourceManager.GetString("DASPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code.
        /// </summary>
        public static string DASPLCD {
            get {
                return ResourceManager.GetString("DASPLCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Contract No.
        /// </summary>
        public static string DASPPNO {
            get {
                return ResourceManager.GetString("DASPPNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support/Long Term.
        /// </summary>
        public static string DASPTCD {
            get {
                return ResourceManager.GetString("DASPTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Slip No.
        /// </summary>
        public static string DASSLP {
            get {
                return ResourceManager.GetString("DASSLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sts Code.
        /// </summary>
        public static string DASTSCD {
            get {
                return ResourceManager.GetString("DASTSCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradding Company No.
        /// </summary>
        public static string DATCNO {
            get {
                return ResourceManager.GetString("DATCNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Type(Tax).
        /// </summary>
        public static string DATEXRT {
            get {
                return ResourceManager.GetString("DATEXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Category.
        /// </summary>
        public static string DATRDCD {
            get {
                return ResourceManager.GetString("DATRDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Amount.
        /// </summary>
        public static string DATRFAT {
            get {
                return ResourceManager.GetString("DATRFAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U/P Of Tariff.
        /// </summary>
        public static string DATRFUP {
            get {
                return ResourceManager.GetString("DATRFUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transection Date.
        /// </summary>
        public static string DATRNDT {
            get {
                return ResourceManager.GetString("DATRNDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Paid  To.
        /// </summary>
        public static string DATRPDT {
            get {
                return ResourceManager.GetString("DATRPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry No.
        /// </summary>
        public static string DATRUCK {
            get {
                return ResourceManager.GetString("DATRUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.P/U Of Tariff.
        /// </summary>
        public static string DATRUPU {
            get {
                return ResourceManager.GetString("DATRUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        public static string DATXCD {
            get {
                return ResourceManager.GetString("DATXCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate(Tax).
        /// </summary>
        public static string DATXEXR {
            get {
                return ResourceManager.GetString("DATXEXR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        public static string DATXRT {
            get {
                return ResourceManager.GetString("DATXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Update.
        /// </summary>
        public static string DAUPDT {
            get {
                return ResourceManager.GetString("DAUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U/P Of Hndl Chrg Frt.
        /// </summary>
        public static string DAUPHFR {
            get {
                return ResourceManager.GetString("DAUPHFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up/U Hndl Chrg Frt .
        /// </summary>
        public static string DAUPUHF {
            get {
                return ResourceManager.GetString("DAUPUHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management No.
        /// </summary>
        public static string DAUSMNG {
            get {
                return ResourceManager.GetString("DAUSMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code.
        /// </summary>
        public static string DAUSRCD {
            get {
                return ResourceManager.GetString("DAUSRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessl.
        /// </summary>
        public static string DAVESEL {
            get {
                return ResourceManager.GetString("DAVESEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation Id.
        /// </summary>
        public static string DAWSID {
            get {
                return ResourceManager.GetString("DAWSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight .
        /// </summary>
        public static string DAWT {
            get {
                return ResourceManager.GetString("DAWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Code.
        /// </summary>
        public static string DAWTCD {
            get {
                return ResourceManager.GetString("DAWTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield Amount.
        /// </summary>
        public static string DAYLDAT {
            get {
                return ResourceManager.GetString("DAYLDAT", resourceCulture);
            }
        }
    }
}
