//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources.View.SalesPurchase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.View.SalesPurchase.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Sale Purchase.
        /// </summary>
        public static string ChangeTitle {
            get {
                return ResourceManager.GetString("ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select row to delete !.
        /// </summary>
        public static string ErrorNoRowSelect {
            get {
                return ResourceManager.GetString("ErrorNoRowSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Sale Purchase.
        /// </summary>
        public static string InsertTitle {
            get {
                return ResourceManager.GetString("InsertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP code already in used.
        /// </summary>
        public static string IsUsed {
            get {
                return ResourceManager.GetString("IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUSINESS TYPE.
        /// </summary>
        public static string MABUZCD {
            get {
                return ResourceManager.GetString("MABUZCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLLECTION TERM.
        /// </summary>
        public static string MACLTRM {
            get {
                return ResourceManager.GetString("MACLTRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRY CODE.
        /// </summary>
        public static string MACNTRC {
            get {
                return ResourceManager.GetString("MACNTRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN CHARGE.
        /// </summary>
        public static string MAIDCD {
            get {
                return ResourceManager.GetString("MAIDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULATION TYPE.
        /// </summary>
        public static string MAPCALC {
            get {
                return ResourceManager.GetString("MAPCALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSING DATE.
        /// </summary>
        public static string MAPCLSD {
            get {
                return ResourceManager.GetString("MAPCLSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY CODE.
        /// </summary>
        public static string MAPCRCD {
            get {
                return ResourceManager.GetString("MAPCRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAYS IN MONTH.
        /// </summary>
        public static string MAPDAYS {
            get {
                return ResourceManager.GetString("MAPDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFERRING.
        /// </summary>
        public static string MAPDFER {
            get {
                return ResourceManager.GetString("MAPDFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTLEMENT.
        /// </summary>
        public static string MAPSETL {
            get {
                return ResourceManager.GetString("MAPSETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE OF DUE DATE.
        /// </summary>
        public static string MAPTDUE {
            get {
                return ResourceManager.GetString("MAPTDUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX CODE.
        /// </summary>
        public static string MAPTXCD {
            get {
                return ResourceManager.GetString("MAPTXCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT TERM.
        /// </summary>
        public static string MAPYTRM {
            get {
                return ResourceManager.GetString("MAPYTRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER DATE.
        /// </summary>
        public static string MARGSDT {
            get {
                return ResourceManager.GetString("MARGSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER TIME.
        /// </summary>
        public static string MARGSTM {
            get {
                return ResourceManager.GetString("MARGSTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULATION TYPE.
        /// </summary>
        public static string MASCALC {
            get {
                return ResourceManager.GetString("MASCALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSING DATE.
        /// </summary>
        public static string MASCLSD {
            get {
                return ResourceManager.GetString("MASCLSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY CODE.
        /// </summary>
        public static string MASCRCD {
            get {
                return ResourceManager.GetString("MASCRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAYS IN MONTH.
        /// </summary>
        public static string MASDAYS {
            get {
                return ResourceManager.GetString("MASDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFERRING.
        /// </summary>
        public static string MASDFER {
            get {
                return ResourceManager.GetString("MASDFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS 1.
        /// </summary>
        public static string MASPAD1 {
            get {
                return ResourceManager.GetString("MASPAD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS 2.
        /// </summary>
        public static string MASPAD2 {
            get {
                return ResourceManager.GetString("MASPAD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS 3.
        /// </summary>
        public static string MASPAD3 {
            get {
                return ResourceManager.GetString("MASPAD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/P CODE.
        /// </summary>
        public static string MASPCD {
            get {
                return ResourceManager.GetString("MASPCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES/PURCHASE.
        /// </summary>
        public static string MASPCTG {
            get {
                return ResourceManager.GetString("MASPCTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES/PURCHASE.
        /// </summary>
        public static string MASPCTGNM {
            get {
                return ResourceManager.GetString("MASPCTGNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAX NO..
        /// </summary>
        public static string MASPFAX {
            get {
                return ResourceManager.GetString("MASPFAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/P NAME.
        /// </summary>
        public static string MASPNM {
            get {
                return ResourceManager.GetString("MASPNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHORT NAME.
        /// </summary>
        public static string MASPSNM {
            get {
                return ResourceManager.GetString("MASPSNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEL NO..
        /// </summary>
        public static string MASPTEL {
            get {
                return ResourceManager.GetString("MASPTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTLEMENT.
        /// </summary>
        public static string MASSETL {
            get {
                return ResourceManager.GetString("MASSETL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE OF DUE DATE.
        /// </summary>
        public static string MASTDUE {
            get {
                return ResourceManager.GetString("MASTDUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Purchase Master.
        /// </summary>
        public static string MasterTitle {
            get {
                return ResourceManager.GetString("MasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX CODE.
        /// </summary>
        public static string MASTXCD {
            get {
                return ResourceManager.GetString("MASTXCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF UPDATE.
        /// </summary>
        public static string MAUPDT {
            get {
                return ResourceManager.GetString("MAUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TIME.
        /// </summary>
        public static string MAUPDTM {
            get {
                return ResourceManager.GetString("MAUPDTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {0} characters..
        /// </summary>
        public static string Maxlength {
            get {
                return ResourceManager.GetString("Maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value less than or equal to {0}..
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no less than {0} characters..
        /// </summary>
        public static string Minlength {
            get {
                return ResourceManager.GetString("Minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number..
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sp code ....
        /// </summary>
        public static string PlaceholderTextSearch {
            get {
                return ResourceManager.GetString("PlaceholderTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
    }
}
