//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources.View.UserID {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.View.UserID.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User ID.
        /// </summary>
        public static string ChangeTitle {
            get {
                return ResourceManager.GetString("ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert User ID.
        /// </summary>
        public static string InsertTitle {
            get {
                return ResourceManager.GetString("InsertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a number..
        /// </summary>
        public static string IsNumber {
            get {
                return ResourceManager.GetString("IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID Master.
        /// </summary>
        public static string MasterTitle {
            get {
                return ResourceManager.GetString("MasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {0} characters..
        /// </summary>
        public static string Maxlength {
            get {
                return ResourceManager.GetString("Maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID CODE.
        /// </summary>
        public static string MCIDCD {
            get {
                return ResourceManager.GetString("MCIDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string MCIDNM {
            get {
                return ResourceManager.GetString("MCIDNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string MCPASS {
            get {
                return ResourceManager.GetString("MCPASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER DATE.
        /// </summary>
        public static string MCRGSDT {
            get {
                return ResourceManager.GetString("MCRGSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER TIME.
        /// </summary>
        public static string MCRGSTM {
            get {
                return ResourceManager.GetString("MCRGSTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECURITY LEVEL.
        /// </summary>
        public static string MCSCTLV {
            get {
                return ResourceManager.GetString("MCSCTLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECTION.
        /// </summary>
        public static string MCSCTNC {
            get {
                return ResourceManager.GetString("MCSCTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF UPDATE.
        /// </summary>
        public static string MCUPDT {
            get {
                return ResourceManager.GetString("MCUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TIME.
        /// </summary>
        public static string MCUPDTM {
            get {
                return ResourceManager.GetString("MCUPDTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no less than {0} characters..
        /// </summary>
        public static string Minlength {
            get {
                return ResourceManager.GetString("Minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user id ....
        /// </summary>
        public static string PlaceholderTextSearch {
            get {
                return ResourceManager.GetString("PlaceholderTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code already in used.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter this field.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
    }
}
