//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources.View.INV001 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.View.INV001.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment No.
        /// </summary>
        public static string CAADJNO {
            get {
                return ResourceManager.GetString("CAADJNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anneal Cmpltd Date.
        /// </summary>
        public static string CAANNDT {
            get {
                return ResourceManager.GetString("CAANNDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesize(Length).
        /// </summary>
        public static string CABSZL {
            get {
                return ResourceManager.GetString("CABSZL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesize(Thk).
        /// </summary>
        public static string CABSZT {
            get {
                return ResourceManager.GetString("CABSZT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesize(Width).
        /// </summary>
        public static string CABSZW {
            get {
                return ResourceManager.GetString("CABSZW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Weight.
        /// </summary>
        public static string CACALWT {
            get {
                return ResourceManager.GetString("CACALWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coilid.
        /// </summary>
        public static string CACILID {
            get {
                return ResourceManager.GetString("CACILID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coilod.
        /// </summary>
        public static string CACILOD {
            get {
                return ResourceManager.GetString("CACILOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination(Length).
        /// </summary>
        public static string CACMBL {
            get {
                return ResourceManager.GetString("CACMBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination(Thk).
        /// </summary>
        public static string CACMBT {
            get {
                return ResourceManager.GetString("CACMBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination(Width).
        /// </summary>
        public static string CACMBW {
            get {
                return ResourceManager.GetString("CACMBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity Code.
        /// </summary>
        public static string CACMDCD {
            get {
                return ResourceManager.GetString("CACMDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating.
        /// </summary>
        public static string CACOAT {
            get {
                return ResourceManager.GetString("CACOAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coatingwt(Back).
        /// </summary>
        public static string CACOATB {
            get {
                return ResourceManager.GetString("CACOATB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coatingwt(Front).
        /// </summary>
        public static string CACOATF {
            get {
                return ResourceManager.GetString("CACOATF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Lose.
        /// </summary>
        public static string CACRLOS {
            get {
                return ResourceManager.GetString("CACRLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string CACRRCD {
            get {
                return ResourceManager.GetString("CACRRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string CACSTCD {
            get {
                return ResourceManager.GetString("CACSTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Hndl Charge.
        /// </summary>
        public static string CACSTHC {
            get {
                return ResourceManager.GetString("CACSTHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No Of P-Cnt No.
        /// </summary>
        public static string CACTITM {
            get {
                return ResourceManager.GetString("CACTITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Mark 1.
        /// </summary>
        public static string CACTLM1 {
            get {
                return ResourceManager.GetString("CACTLM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cstm Hnd Chrg Pd To.
        /// </summary>
        public static string CACTPDT {
            get {
                return ResourceManager.GetString("CACTPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Contract No.
        /// </summary>
        public static string CACTRNO {
            get {
                return ResourceManager.GetString("CACTRNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string CACTRTP {
            get {
                return ResourceManager.GetString("CACTRTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Spec.
        /// </summary>
        public static string CACTSPC {
            get {
                return ResourceManager.GetString("CACTSPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cstm Hnd Chrg U/P.
        /// </summary>
        public static string CACTUP {
            get {
                return ResourceManager.GetString("CACTUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cstm Hnd Chrg Up/U.
        /// </summary>
        public static string CACTUPU {
            get {
                return ResourceManager.GetString("CACTUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic Current Code.
        /// </summary>
        public static string CADCRCD {
            get {
                return ResourceManager.GetString("CADCRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/I No.
        /// </summary>
        public static string CADINO {
            get {
                return ResourceManager.GetString("CADINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date To User.
        /// </summary>
        public static string CADLDTT {
            get {
                return ResourceManager.GetString("CADLDTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string CADLVDT {
            get {
                return ResourceManager.GetString("CADLVDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery To.
        /// </summary>
        public static string CADLVTO {
            get {
                return ResourceManager.GetString("CADLVTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Code.
        /// </summary>
        public static string CADMGCD {
            get {
                return ResourceManager.GetString("CADMGCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dencity.
        /// </summary>
        public static string CADNSTY {
            get {
                return ResourceManager.GetString("CADNSTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/O No.
        /// </summary>
        public static string CADONO {
            get {
                return ResourceManager.GetString("CADONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposity/Asset Code.
        /// </summary>
        public static string CADPSCD {
            get {
                return ResourceManager.GetString("CADPSCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CADSTNC {
            get {
                return ResourceManager.GetString("CADSTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Code.
        /// </summary>
        public static string CADTCD {
            get {
                return ResourceManager.GetString("CADTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string CAEXRT {
            get {
                return ResourceManager.GetString("CAEXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Tax.
        /// </summary>
        public static string CAEXRTT {
            get {
                return ResourceManager.GetString("CAEXRTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string CAGRADE {
            get {
                return ResourceManager.GetString("CAGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hndl Chrg Amount.
        /// </summary>
        public static string CAHCGAT {
            get {
                return ResourceManager.GetString("CAHCGAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idcode.
        /// </summary>
        public static string CAIDCD {
            get {
                return ResourceManager.GetString("CAIDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Induction.
        /// </summary>
        public static string CAINDCT {
            get {
                return ResourceManager.GetString("CAINDCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtinpackage.
        /// </summary>
        public static string CAINPCK {
            get {
                return ResourceManager.GetString("CAINPCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prc Chrg Amp(Intrnl).
        /// </summary>
        public static string CAINTPC {
            get {
                return ResourceManager.GetString("CAINTPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pck Chrg Amt (Intrnl).
        /// </summary>
        public static string CAINTPK {
            get {
                return ResourceManager.GetString("CAINTPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory No.
        /// </summary>
        public static string CAINVNO {
            get {
                return ResourceManager.GetString("CAINVNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Status.
        /// </summary>
        public static string CAINVST {
            get {
                return ResourceManager.GetString("CAINVST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Type.
        /// </summary>
        public static string CAINVTP {
            get {
                return ResourceManager.GetString("CAINVTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection No.
        /// </summary>
        public static string CAISPNO {
            get {
                return ResourceManager.GetString("CAISPNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string CAISSDT {
            get {
                return ResourceManager.GetString("CAISSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No (Sales Slip).
        /// </summary>
        public static string CAISSLP {
            get {
                return ResourceManager.GetString("CAISSLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        public static string CAIVCDT {
            get {
                return ResourceManager.GetString("CAIVCDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No Of Job No.
        /// </summary>
        public static string CAJBITM {
            get {
                return ResourceManager.GetString("CAJBITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job No.
        /// </summary>
        public static string CAJOBNO {
            get {
                return ResourceManager.GetString("CAJOBNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locationcode.
        /// </summary>
        public static string CALCTCD {
            get {
                return ResourceManager.GetString("CALCTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine No.
        /// </summary>
        public static string CAMCHNO {
            get {
                return ResourceManager.GetString("CAMCHNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Coil Spec.
        /// </summary>
        public static string CAMCSPC {
            get {
                return ResourceManager.GetString("CAMCSPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker Code.
        /// </summary>
        public static string CAMKCD {
            get {
                return ResourceManager.GetString("CAMKCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No Of O.E.No.
        /// </summary>
        public static string CAOEITM {
            get {
                return ResourceManager.GetString("CAOEITM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Entry No.
        /// </summary>
        public static string CAOENO {
            get {
                return ResourceManager.GetString("CAOENO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O.No(Order Entry).
        /// </summary>
        public static string CAOEPO {
            get {
                return ResourceManager.GetString("CAOEPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original No.
        /// </summary>
        public static string CAOGLNO {
            get {
                return ResourceManager.GetString("CAOGLNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No.
        /// </summary>
        public static string CAORDNO {
            get {
                return ResourceManager.GetString("CAORDNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Date.
        /// </summary>
        public static string CAPAYDT {
            get {
                return ResourceManager.GetString("CAPAYDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paking Date.
        /// </summary>
        public static string CAPCKDT {
            get {
                return ResourceManager.GetString("CAPCKDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paking Make.
        /// </summary>
        public static string CAPCKM {
            get {
                return ResourceManager.GetString("CAPCKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paking No.
        /// </summary>
        public static string CAPCKNO {
            get {
                return ResourceManager.GetString("CAPCKNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paking Type.
        /// </summary>
        public static string CAPCKTP {
            get {
                return ResourceManager.GetString("CAPCKTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paking Weight.
        /// </summary>
        public static string CAPCKWT {
            get {
                return ResourceManager.GetString("CAPCKWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prchs Frt U/P.
        /// </summary>
        public static string CAPFRUP {
            get {
                return ResourceManager.GetString("CAPFRUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prchs Frt U.P/U.
        /// </summary>
        public static string CAPFUPU {
            get {
                return ResourceManager.GetString("CAPFUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Invoice Date.
        /// </summary>
        public static string CAPIVDT {
            get {
                return ResourceManager.GetString("CAPIVDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Invoice No.
        /// </summary>
        public static string CAPIVNO {
            get {
                return ResourceManager.GetString("CAPIVNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pck Chrg Amt (Supcnt).
        /// </summary>
        public static string CAPKATB {
            get {
                return ResourceManager.GetString("CAPKATB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O.Date.
        /// </summary>
        public static string CAPODT {
            get {
                return ResourceManager.GetString("CAPODT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prc Chrg Amp(Supcnt).
        /// </summary>
        public static string CAPRATB {
            get {
                return ResourceManager.GetString("CAPRATB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Date.
        /// </summary>
        public static string CAPRCDT {
            get {
                return ResourceManager.GetString("CAPRCDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Type.
        /// </summary>
        public static string CAPRCTP {
            get {
                return ResourceManager.GetString("CAPRCTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string CAPRDNM {
            get {
                return ResourceManager.GetString("CAPRDNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase U/B(Dcurr).
        /// </summary>
        public static string CAPRUPD {
            get {
                return ResourceManager.GetString("CAPRUPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase U.B/U.
        /// </summary>
        public static string CAPRUPU {
            get {
                return ResourceManager.GetString("CAPRUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Slip No.
        /// </summary>
        public static string CAPSLP {
            get {
                return ResourceManager.GetString("CAPSLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itm No (Prchs Slp No).
        /// </summary>
        public static string CAPSLPI {
            get {
                return ResourceManager.GetString("CAPSLPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prch Frt Amount.
        /// </summary>
        public static string CAPUFAT {
            get {
                return ResourceManager.GetString("CAPUFAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prchs Frt Paid To.
        /// </summary>
        public static string CAPUFRT {
            get {
                return ResourceManager.GetString("CAPUFRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Amount.
        /// </summary>
        public static string CAPURAT {
            get {
                return ResourceManager.GetString("CAPURAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasegoodcode.
        /// </summary>
        public static string CAPURGD {
            get {
                return ResourceManager.GetString("CAPURGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase U/B.
        /// </summary>
        public static string CAPURUP {
            get {
                return ResourceManager.GetString("CAPURUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string CAQTY {
            get {
                return ResourceManager.GetString("CAQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string CARGSDT {
            get {
                return ResourceManager.GetString("CARGSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present Code.
        /// </summary>
        public static string CARSNCD {
            get {
                return ResourceManager.GetString("CARSNCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Incharge.
        /// </summary>
        public static string CASCTNC {
            get {
                return ResourceManager.GetString("CASCTNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Code.
        /// </summary>
        public static string CASECCD {
            get {
                return ResourceManager.GetString("CASECCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Entry Date.
        /// </summary>
        public static string CASEDT {
            get {
                return ResourceManager.GetString("CASEDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Date.
        /// </summary>
        public static string CASHPDT {
            get {
                return ResourceManager.GetString("CASHPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size(Length).
        /// </summary>
        public static string CASIZEL {
            get {
                return ResourceManager.GetString("CASIZEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size(Thk).
        /// </summary>
        public static string CASIZET {
            get {
                return ResourceManager.GetString("CASIZET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size(Width).
        /// </summary>
        public static string CASIZEW {
            get {
                return ResourceManager.GetString("CASIZEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Unit Weight.
        /// </summary>
        public static string CASLUWT {
            get {
                return ResourceManager.GetString("CASLUWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Month.
        /// </summary>
        public static string CASMNTH {
            get {
                return ResourceManager.GetString("CASMNTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec.
        /// </summary>
        public static string CASPEC {
            get {
                return ResourceManager.GetString("CASPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code.
        /// </summary>
        public static string CASPLCD {
            get {
                return ResourceManager.GetString("CASPLCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Contract No.
        /// </summary>
        public static string CASPPNO {
            get {
                return ResourceManager.GetString("CASPPNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support / Longterm.
        /// </summary>
        public static string CASPTCD {
            get {
                return ResourceManager.GetString("CASPTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Slip No.
        /// </summary>
        public static string CASSLP {
            get {
                return ResourceManager.GetString("CASSLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O.No(Stock Entry).
        /// </summary>
        public static string CASTKPO {
            get {
                return ResourceManager.GetString("CASTKPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stscode.
        /// </summary>
        public static string CASTSCD {
            get {
                return ResourceManager.GetString("CASTSCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item No (Inspctn No).
        /// </summary>
        public static string CASUBNO {
            get {
                return ResourceManager.GetString("CASUBNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tradding Company No.
        /// </summary>
        public static string CATCNO {
            get {
                return ResourceManager.GetString("CATCNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Exchange Rate Type.
        /// </summary>
        public static string CATEXRT {
            get {
                return ResourceManager.GetString("CATEXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Category.
        /// </summary>
        public static string CATRDCD {
            get {
                return ResourceManager.GetString("CATRDCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Amount.
        /// </summary>
        public static string CATRFAT {
            get {
                return ResourceManager.GetString("CATRFAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U/P Of Tariff.
        /// </summary>
        public static string CATRFUP {
            get {
                return ResourceManager.GetString("CATRFUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Paid To.
        /// </summary>
        public static string CATRPDT {
            get {
                return ResourceManager.GetString("CATRPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.P/U Of Tariff.
        /// </summary>
        public static string CATRUPU {
            get {
                return ResourceManager.GetString("CATRUPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        public static string CATXCD {
            get {
                return ResourceManager.GetString("CATXCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Exchange Rate.
        /// </summary>
        public static string CATXEXR {
            get {
                return ResourceManager.GetString("CATXEXR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        public static string CATXRT {
            get {
                return ResourceManager.GetString("CATXRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string CAUPDT {
            get {
                return ResourceManager.GetString("CAUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management No.
        /// </summary>
        public static string CAUSMNG {
            get {
                return ResourceManager.GetString("CAUSMNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Code.
        /// </summary>
        public static string CAUSRCD {
            get {
                return ResourceManager.GetString("CAUSRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessl .
        /// </summary>
        public static string CAVESEL {
            get {
                return ResourceManager.GetString("CAVESEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weigth.
        /// </summary>
        public static string CAWT {
            get {
                return ResourceManager.GetString("CAWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yield Amount.
        /// </summary>
        public static string CAYLDAT {
            get {
                return ResourceManager.GetString("CAYLDAT", resourceCulture);
            }
        }
    }
}
