//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources.View.MA012 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.View.MA012.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Bank Code.
        /// </summary>
        public static string ChangeBankCodeTitle {
            get {
                return ResourceManager.GetString("ChangeBankCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Business Type Code.
        /// </summary>
        public static string ChangeBusinessTypeCodeTitle {
            get {
                return ResourceManager.GetString("ChangeBusinessTypeCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Calculation.
        /// </summary>
        public static string ChangeCalculationTypeTitle {
            get {
                return ResourceManager.GetString("ChangeCalculationTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Commodity.
        /// </summary>
        public static string ChangeCommodityTitle {
            get {
                return ResourceManager.GetString("ChangeCommodityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Contract Type.
        /// </summary>
        public static string ChangeContractTypeTitle {
            get {
                return ResourceManager.GetString("ChangeContractTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Country Code.
        /// </summary>
        public static string ChangeCountryCodeTitle {
            get {
                return ResourceManager.GetString("ChangeCountryCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Currency Code.
        /// </summary>
        public static string ChangeCurrencyCodeTitle {
            get {
                return ResourceManager.GetString("ChangeCurrencyCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Damage Code.
        /// </summary>
        public static string ChangeDamageCodeTitle {
            get {
                return ResourceManager.GetString("ChangeDamageCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Data Type.
        /// </summary>
        public static string ChangeDataTypeTitle {
            get {
                return ResourceManager.GetString("ChangeDataTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Days In Month Master.
        /// </summary>
        public static string ChangeDaysInMonthTitle {
            get {
                return ResourceManager.GetString("ChangeDaysInMonthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Delivery Condition.
        /// </summary>
        public static string ChangeDeliveryConditionTitle {
            get {
                return ResourceManager.GetString("ChangeDeliveryConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Due Date Type Master.
        /// </summary>
        public static string ChangeDueDateTypeTitle {
            get {
                return ResourceManager.GetString("ChangeDueDateTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Exchange Rate Type.
        /// </summary>
        public static string ChangeExchangeRateTypeTitle {
            get {
                return ResourceManager.GetString("ChangeExchangeRateTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Grade.
        /// </summary>
        public static string ChangeGradeTitle {
            get {
                return ResourceManager.GetString("ChangeGradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Interrupted Reason Code.
        /// </summary>
        public static string ChangeInterruptedReasonCodeTitle {
            get {
                return ResourceManager.GetString("ChangeInterruptedReasonCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Inventory Status.
        /// </summary>
        public static string ChangeInventoryStatusTitle {
            get {
                return ResourceManager.GetString("ChangeInventoryStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Inventory Type.
        /// </summary>
        public static string ChangeInventoryTypeTitle {
            get {
                return ResourceManager.GetString("ChangeInventoryTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log Type.
        /// </summary>
        public static string ChangeLogTypeTitle {
            get {
                return ResourceManager.GetString("ChangeLogTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Machine No.
        /// </summary>
        public static string ChangeMachineNoTitle {
            get {
                return ResourceManager.GetString("ChangeMachineNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Maker Code.
        /// </summary>
        public static string ChangeMakerCodeTitle {
            get {
                return ResourceManager.GetString("ChangeMakerCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Money Type.
        /// </summary>
        public static string ChangeMoneyTypeTitle {
            get {
                return ResourceManager.GetString("ChangeMoneyTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Packing Type.
        /// </summary>
        public static string ChangePackingTypeTitle {
            get {
                return ResourceManager.GetString("ChangePackingTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Price Term.
        /// </summary>
        public static string ChangePriceTermTitle {
            get {
                return ResourceManager.GetString("ChangePriceTermTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Reason For Changing Code.
        /// </summary>
        public static string ChangeReasonForChangingCodeTitle {
            get {
                return ResourceManager.GetString("ChangeReasonForChangingCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Section Code.
        /// </summary>
        public static string ChangeSectionCodeTitle {
            get {
                return ResourceManager.GetString("ChangeSectionCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Settlement Term.
        /// </summary>
        public static string ChangeSettlementTermTitle {
            get {
                return ResourceManager.GetString("ChangeSettlementTermTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Shift Code.
        /// </summary>
        public static string ChangeShiftCodeTitle {
            get {
                return ResourceManager.GetString("ChangeShiftCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status Code .
        /// </summary>
        public static string ChangeStatusCodeTitle {
            get {
                return ResourceManager.GetString("ChangeStatusCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Trade Category .
        /// </summary>
        public static string ChangeTradeCategoryTitle {
            get {
                return ResourceManager.GetString("ChangeTradeCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Type of Terms.
        /// </summary>
        public static string ChangeTypeofTermsTitle {
            get {
                return ResourceManager.GetString("ChangeTypeofTermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Unit Price Unit .
        /// </summary>
        public static string ChangeUnitPriceUnitTitle {
            get {
                return ResourceManager.GetString("ChangeUnitPriceUnitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Weigth Display Code.
        /// </summary>
        public static string ChangeWeightDisplayCodeTitle {
            get {
                return ResourceManager.GetString("ChangeWeightDisplayCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Weight Calculation Code.
        /// </summary>
        public static string EditWeightCalculationCodeTittle {
            get {
                return ResourceManager.GetString("EditWeightCalculationCodeTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select row to delete !.
        /// </summary>
        public static string ErrorNoRowSelect {
            get {
                return ResourceManager.GetString("ErrorNoRowSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Bank Code.
        /// </summary>
        public static string InsertBankCodeTitle {
            get {
                return ResourceManager.GetString("InsertBankCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Business Type Code.
        /// </summary>
        public static string InsertBusinessTypeCodeTitle {
            get {
                return ResourceManager.GetString("InsertBusinessTypeCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Calculation.
        /// </summary>
        public static string InsertCalcualationTypeTitle {
            get {
                return ResourceManager.GetString("InsertCalcualationTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Commodity.
        /// </summary>
        public static string InsertCommodityTitle {
            get {
                return ResourceManager.GetString("InsertCommodityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Contract Type.
        /// </summary>
        public static string InsertContractTypeTitle {
            get {
                return ResourceManager.GetString("InsertContractTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Country Code.
        /// </summary>
        public static string InsertCountryCodeTitle {
            get {
                return ResourceManager.GetString("InsertCountryCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Currency Code.
        /// </summary>
        public static string InsertCurrencyCodeTitle {
            get {
                return ResourceManager.GetString("InsertCurrencyCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Damage Code.
        /// </summary>
        public static string InsertDamageCodeTitle {
            get {
                return ResourceManager.GetString("InsertDamageCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Data Type.
        /// </summary>
        public static string InsertDataTypeTitle {
            get {
                return ResourceManager.GetString("InsertDataTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Days In Month Master.
        /// </summary>
        public static string InsertDaysInMonthTitle {
            get {
                return ResourceManager.GetString("InsertDaysInMonthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Delivery Condition.
        /// </summary>
        public static string InsertDeliveryConditionTitle {
            get {
                return ResourceManager.GetString("InsertDeliveryConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Due Date Type Master.
        /// </summary>
        public static string InsertDueDateTypeTitle {
            get {
                return ResourceManager.GetString("InsertDueDateTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Exchange Rate Type.
        /// </summary>
        public static string InsertExchangeRateTypeTitle {
            get {
                return ResourceManager.GetString("InsertExchangeRateTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Grade.
        /// </summary>
        public static string InsertGradeTitle {
            get {
                return ResourceManager.GetString("InsertGradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Interrupted Reason Code.
        /// </summary>
        public static string InsertInterruptedReasonCodetTitle {
            get {
                return ResourceManager.GetString("InsertInterruptedReasonCodetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Inventory Status.
        /// </summary>
        public static string InsertInventoryStatusTitle {
            get {
                return ResourceManager.GetString("InsertInventoryStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Inventory Type.
        /// </summary>
        public static string InsertInventoryTypeTitle {
            get {
                return ResourceManager.GetString("InsertInventoryTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Log Type.
        /// </summary>
        public static string InsertLogTypeTitle {
            get {
                return ResourceManager.GetString("InsertLogTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Machine No.
        /// </summary>
        public static string InsertMachineNoTitle {
            get {
                return ResourceManager.GetString("InsertMachineNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Maker Code.
        /// </summary>
        public static string InsertMakerCodeTitle {
            get {
                return ResourceManager.GetString("InsertMakerCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Money Type.
        /// </summary>
        public static string InsertMoneyTypeTitle {
            get {
                return ResourceManager.GetString("InsertMoneyTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Packing Type.
        /// </summary>
        public static string InsertPackingTypeTitle {
            get {
                return ResourceManager.GetString("InsertPackingTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Price Term.
        /// </summary>
        public static string InsertPriceTermTitle {
            get {
                return ResourceManager.GetString("InsertPriceTermTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Reason For Changing Code.
        /// </summary>
        public static string InsertReasonForChangingCodeTitle {
            get {
                return ResourceManager.GetString("InsertReasonForChangingCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Section Code.
        /// </summary>
        public static string InsertSectionCodeTitle {
            get {
                return ResourceManager.GetString("InsertSectionCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Settlement Term.
        /// </summary>
        public static string InsertSettlementTermTitle {
            get {
                return ResourceManager.GetString("InsertSettlementTermTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Shift Code.
        /// </summary>
        public static string InsertShiftCodeTitle {
            get {
                return ResourceManager.GetString("InsertShiftCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Status Code.
        /// </summary>
        public static string InsertStatusCodeTitle {
            get {
                return ResourceManager.GetString("InsertStatusCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Trade Category .
        /// </summary>
        public static string InsertTradeCategoryTitle {
            get {
                return ResourceManager.GetString("InsertTradeCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Type of Terms.
        /// </summary>
        public static string InsertTypeofTermsTitle {
            get {
                return ResourceManager.GetString("InsertTypeofTermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Unit Price Unit.
        /// </summary>
        public static string InsertUnitPriceUnitTitle {
            get {
                return ResourceManager.GetString("InsertUnitPriceUnitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Weight Calculation Code.
        /// </summary>
        public static string InsertWeightCalculationCodeTittle {
            get {
                return ResourceManager.GetString("InsertWeightCalculationCodeTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Weigth Display Code.
        /// </summary>
        public static string InsertWeightDisplayCodeTitle {
            get {
                return ResourceManager.GetString("InsertWeightDisplayCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR code already in used.
        /// </summary>
        public static string IsUsed {
            get {
                return ResourceManager.GetString("IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code Master.
        /// </summary>
        public static string MasterBankCodeTitle {
            get {
                return ResourceManager.GetString("MasterBankCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Code Master.
        /// </summary>
        public static string MasterBusinessTypeCodeTitle {
            get {
                return ResourceManager.GetString("MasterBusinessTypeCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Type Master.
        /// </summary>
        public static string MasterCalcualationTypeTitle {
            get {
                return ResourceManager.GetString("MasterCalcualationTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity Master.
        /// </summary>
        public static string MasterCommodityTitle {
            get {
                return ResourceManager.GetString("MasterCommodityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type Master.
        /// </summary>
        public static string MasterContractTypeTitle {
            get {
                return ResourceManager.GetString("MasterContractTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code Master.
        /// </summary>
        public static string MasterCountryCodeTitle {
            get {
                return ResourceManager.GetString("MasterCountryCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code Master.
        /// </summary>
        public static string MasterCurrencyCodeTitle {
            get {
                return ResourceManager.GetString("MasterCurrencyCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Code Master.
        /// </summary>
        public static string MasterDamageCodeTitle {
            get {
                return ResourceManager.GetString("MasterDamageCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type Master.
        /// </summary>
        public static string MasterDataTypeTitle {
            get {
                return ResourceManager.GetString("MasterDataTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days In Month Master.
        /// </summary>
        public static string MasterDaysInMonthTitle {
            get {
                return ResourceManager.GetString("MasterDaysInMonthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Condition Master.
        /// </summary>
        public static string MasterDeliveryConditionTitle {
            get {
                return ResourceManager.GetString("MasterDeliveryConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date Type Master.
        /// </summary>
        public static string MasterDueDateTypeTitle {
            get {
                return ResourceManager.GetString("MasterDueDateTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Type Master.
        /// </summary>
        public static string MasterExchangeRateTypeTitle {
            get {
                return ResourceManager.GetString("MasterExchangeRateTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Master.
        /// </summary>
        public static string MasterGradeTitle {
            get {
                return ResourceManager.GetString("MasterGradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupted Reason Code Master.
        /// </summary>
        public static string MasterInterruptedReasonCodeTitle {
            get {
                return ResourceManager.GetString("MasterInterruptedReasonCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Status Master.
        /// </summary>
        public static string MasterInventoryStatusTitle {
            get {
                return ResourceManager.GetString("MasterInventoryStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Type Master.
        /// </summary>
        public static string MasterInventoryTypeTitle {
            get {
                return ResourceManager.GetString("MasterInventoryTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type Master.
        /// </summary>
        public static string MasterLogTypeTitle {
            get {
                return ResourceManager.GetString("MasterLogTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Machine No.
        /// </summary>
        public static string MasterMachineNoTitle {
            get {
                return ResourceManager.GetString("MasterMachineNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker Code Master.
        /// </summary>
        public static string MasterMakerCodeTitle {
            get {
                return ResourceManager.GetString("MasterMakerCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Type Master.
        /// </summary>
        public static string MasterMoneyTypeTitle {
            get {
                return ResourceManager.GetString("MasterMoneyTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Type Master.
        /// </summary>
        public static string MasterPackingTypeTitle {
            get {
                return ResourceManager.GetString("MasterPackingTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Term Master.
        /// </summary>
        public static string MasterPriceTermTitle {
            get {
                return ResourceManager.GetString("MasterPriceTermTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason For Changing Code Master.
        /// </summary>
        public static string MasterReasonForChangingCodeTitle {
            get {
                return ResourceManager.GetString("MasterReasonForChangingCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Code Master.
        /// </summary>
        public static string MasterSectionCodeTitle {
            get {
                return ResourceManager.GetString("MasterSectionCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Term Master.
        /// </summary>
        public static string MasterSettlementTermTitle {
            get {
                return ResourceManager.GetString("MasterSettlementTermTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Code Master.
        /// </summary>
        public static string MasterShiftCodeTitle {
            get {
                return ResourceManager.GetString("MasterShiftCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code Master.
        /// </summary>
        public static string MasterStatusCodeTitle {
            get {
                return ResourceManager.GetString("MasterStatusCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Category Master.
        /// </summary>
        public static string MasterTradeCategoryTitle {
            get {
                return ResourceManager.GetString("MasterTradeCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Terms Master.
        /// </summary>
        public static string MasterTypeofTermsTitle {
            get {
                return ResourceManager.GetString("MasterTypeofTermsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price Unit Master.
        /// </summary>
        public static string MasterUnitPriceUnitTitle {
            get {
                return ResourceManager.GetString("MasterUnitPriceUnitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weigth Display Code Master.
        /// </summary>
        public static string MasterWeightDisplayCodeTitle {
            get {
                return ResourceManager.GetString("MasterWeightDisplayCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {0} characters..
        /// </summary>
        public static string Maxlength {
            get {
                return ResourceManager.GetString("Maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no less than {0} characters..
        /// </summary>
        public static string Minlength {
            get {
                return ResourceManager.GetString("Minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASSIFICATION CODE.
        /// </summary>
        public static string MNCLSCD {
            get {
                return ResourceManager.GetString("MNCLSCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER DATE.
        /// </summary>
        public static string MNRGSDT {
            get {
                return ResourceManager.GetString("MNRGSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER TIME.
        /// </summary>
        public static string MNRGSTM {
            get {
                return ResourceManager.GetString("MNRGSTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR CODE.
        /// </summary>
        public static string MNSRCD {
            get {
                return ResourceManager.GetString("MNSRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR NAME.
        /// </summary>
        public static string MNSRNM {
            get {
                return ResourceManager.GetString("MNSRNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR SHORT NAME.
        /// </summary>
        public static string MNSRSNM {
            get {
                return ResourceManager.GetString("MNSRSNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF UPDATE.
        /// </summary>
        public static string MNUPDT {
            get {
                return ResourceManager.GetString("MNUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TIME.
        /// </summary>
        public static string MNUPDTM {
            get {
                return ResourceManager.GetString("MNUPDTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sr code ....
        /// </summary>
        public static string PlaceholderTextSearch {
            get {
                return ResourceManager.GetString("PlaceholderTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Raw Material Type.
        /// </summary>
        public static string RawMaterialTypeMasterInsert {
            get {
                return ResourceManager.GetString("RawMaterialTypeMasterInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw MaterialType Master.
        /// </summary>
        public static string RawMaterialTypeMasterTitle {
            get {
                return ResourceManager.GetString("RawMaterialTypeMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Raw Material Type.
        /// </summary>
        public static string RawMaterialTypeMasterUpdate {
            get {
                return ResourceManager.GetString("RawMaterialTypeMasterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter this field.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Calculation Code Master.
        /// </summary>
        public static string WeightCalculationCodeMasterTittle {
            get {
                return ResourceManager.GetString("WeightCalculationCodeMasterTittle", resourceCulture);
            }
        }
    }
}
