//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources.View.RawMaterialType {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.View.RawMaterialType.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Type Insert.
        /// </summary>
        public static string InsertTitle {
            get {
                return ResourceManager.GetString("InsertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a number..
        /// </summary>
        public static string IsNumber {
            get {
                return ResourceManager.GetString("IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Type Master.
        /// </summary>
        public static string MasterTitle {
            get {
                return ResourceManager.GetString("MasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {0} characters..
        /// </summary>
        public static string Maxlength {
            get {
                return ResourceManager.GetString("Maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no less than {0} characters..
        /// </summary>
        public static string Minlength {
            get {
                return ResourceManager.GetString("Minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Raw Material Type code ....
        /// </summary>
        public static string PlaceholderTextSearch {
            get {
                return ResourceManager.GetString("PlaceholderTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Type code already in used.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter this feild.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Type Code.
        /// </summary>
        public static string RMTCD {
            get {
                return ResourceManager.GetString("RMTCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER DATE.
        /// </summary>
        public static string RMTGSDT {
            get {
                return ResourceManager.GetString("RMTGSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER TIME.
        /// </summary>
        public static string RMTGSTM {
            get {
                return ResourceManager.GetString("RMTGSTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Type Name.
        /// </summary>
        public static string RMTNM {
            get {
                return ResourceManager.GetString("RMTNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DATE.
        /// </summary>
        public static string RMTUPDT {
            get {
                return ResourceManager.GetString("RMTUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TIME.
        /// </summary>
        public static string RMTUPTM {
            get {
                return ResourceManager.GetString("RMTUPTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select row to delete !.
        /// </summary>
        public static string SelectRow {
            get {
                return ResourceManager.GetString("SelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Type Update.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
    }
}
