//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemMenuMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemMenuMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.ItemMenuMaster", typeof(ItemMenuMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code Master.
        /// </summary>
        public static string BankCodeMaster {
            get {
                return ResourceManager.GetString("BankCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type Code Master.
        /// </summary>
        public static string BusinessTypeCodeMaster {
            get {
                return ResourceManager.GetString("BusinessTypeCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Type.
        /// </summary>
        public static string CalculationTypeMaster {
            get {
                return ResourceManager.GetString("CalculationTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Date.
        /// </summary>
        public static string ClosingDateMaster {
            get {
                return ResourceManager.GetString("ClosingDateMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coating.
        /// </summary>
        public static string CoatingMaster {
            get {
                return ResourceManager.GetString("CoatingMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity Code.
        /// </summary>
        public static string CommodityCodeMaster {
            get {
                return ResourceManager.GetString("CommodityCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type Master.
        /// </summary>
        public static string ContractTypeMaster {
            get {
                return ResourceManager.GetString("ContractTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code Master.
        /// </summary>
        public static string CountryCodeMaster {
            get {
                return ResourceManager.GetString("CountryCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string CreditMaster {
            get {
                return ResourceManager.GetString("CreditMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code Master.
        /// </summary>
        public static string CurrencyCodeMaster {
            get {
                return ResourceManager.GetString("CurrencyCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Code Master.
        /// </summary>
        public static string DamageCodeMaster {
            get {
                return ResourceManager.GetString("DamageCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type Master.
        /// </summary>
        public static string DataTypeMaster {
            get {
                return ResourceManager.GetString("DataTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days In Month.
        /// </summary>
        public static string DaysInMonthMaster {
            get {
                return ResourceManager.GetString("DaysInMonthMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Condition Master.
        /// </summary>
        public static string DeliveryConditionMaster {
            get {
                return ResourceManager.GetString("DeliveryConditionMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date Type.
        /// </summary>
        public static string DueDateTypeMaster {
            get {
                return ResourceManager.GetString("DueDateTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string ExchangeRateMaster {
            get {
                return ResourceManager.GetString("ExchangeRateMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate Type Master.
        /// </summary>
        public static string ExchangeRateTypeMaster {
            get {
                return ResourceManager.GetString("ExchangeRateTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Master.
        /// </summary>
        public static string GradeMaster {
            get {
                return ResourceManager.GetString("GradeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupted Reason Code Master.
        /// </summary>
        public static string InterruptedReasonCodeMaster {
            get {
                return ResourceManager.GetString("InterruptedReasonCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Status Master.
        /// </summary>
        public static string InventoryStatusMaster {
            get {
                return ResourceManager.GetString("InventoryStatusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Type Master.
        /// </summary>
        public static string InventoryTypeMaster {
            get {
                return ResourceManager.GetString("InventoryTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationMaster {
            get {
                return ResourceManager.GetString("LocationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Type Master.
        /// </summary>
        public static string LogTypeMaster {
            get {
                return ResourceManager.GetString("LogTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine No Master.
        /// </summary>
        public static string MachineNoMaster {
            get {
                return ResourceManager.GetString("MachineNoMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker Code.
        /// </summary>
        public static string MakerCodeMaster {
            get {
                return ResourceManager.GetString("MakerCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Setting.
        /// </summary>
        public static string MasterSetting {
            get {
                return ResourceManager.GetString("MasterSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Type Master.
        /// </summary>
        public static string MoneyTypeMaster {
            get {
                return ResourceManager.GetString("MoneyTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Type Master.
        /// </summary>
        public static string PackingTypeMaster {
            get {
                return ResourceManager.GetString("PackingTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Term Master.
        /// </summary>
        public static string PriceTermMaster {
            get {
                return ResourceManager.GetString("PriceTermMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Type.
        /// </summary>
        public static string RawMaterialTypeMaster {
            get {
                return ResourceManager.GetString("RawMaterialTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Changing Code Master.
        /// </summary>
        public static string ReasonForChangingCodeMaster {
            get {
                return ResourceManager.GetString("ReasonForChangingCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Purchase.
        /// </summary>
        public static string SalePurchaseMaster {
            get {
                return ResourceManager.GetString("SalePurchaseMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Code Master.
        /// </summary>
        public static string SectionCodeMaster {
            get {
                return ResourceManager.GetString("SectionCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Term Master.
        /// </summary>
        public static string SettlementTermMaster {
            get {
                return ResourceManager.GetString("SettlementTermMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Code Master.
        /// </summary>
        public static string ShiftCodeMaster {
            get {
                return ResourceManager.GetString("ShiftCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec.
        /// </summary>
        public static string SpecMaster {
            get {
                return ResourceManager.GetString("SpecMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Code Master.
        /// </summary>
        public static string StatusCodeMaster {
            get {
                return ResourceManager.GetString("StatusCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Grade.
        /// </summary>
        public static string SteelGradeMaster {
            get {
                return ResourceManager.GetString("SteelGradeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string TaxMaster {
            get {
                return ResourceManager.GetString("TaxMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Category Master.
        /// </summary>
        public static string TradeCategoryMaster {
            get {
                return ResourceManager.GetString("TradeCategoryMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Terms Master.
        /// </summary>
        public static string TypeofTermsMaster {
            get {
                return ResourceManager.GetString("TypeofTermsMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price Unit Master.
        /// </summary>
        public static string UnitPriceUnitMaster {
            get {
                return ResourceManager.GetString("UnitPriceUnitMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserIDMaster {
            get {
                return ResourceManager.GetString("UserIDMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Master.
        /// </summary>
        public static string UserMaster {
            get {
                return ResourceManager.GetString("UserMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Calculation Code.
        /// </summary>
        public static string WeightCalculationCodeMaster {
            get {
                return ResourceManager.GetString("WeightCalculationCodeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Display Code.
        /// </summary>
        public static string WeightDisplayCodeMaster {
            get {
                return ResourceManager.GetString("WeightDisplayCodeMaster", resourceCulture);
            }
        }
    }
}
