//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemMenuRawMaterial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemMenuRawMaterial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.ItemMenuRawMaterial", typeof(ItemMenuRawMaterial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Raw Material Label.
        /// </summary>
        public static string PrintRawMaterialLabel {
            get {
                return ResourceManager.GetString("PrintRawMaterialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Raw Material Receving List.
        /// </summary>
        public static string PrintRawMaterialRecevingList {
            get {
                return ResourceManager.GetString("PrintRawMaterialRecevingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Warehousing Entry.
        /// </summary>
        public static string RawMaterialWarehousingEntry {
            get {
                return ResourceManager.GetString("RawMaterialWarehousingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Raw Material Stock Entry.
        /// </summary>
        public static string RawMaterialWarehousingEntryAdd {
            get {
                return ResourceManager.GetString("RawMaterialWarehousingEntryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Raw Material Stock Entry.
        /// </summary>
        public static string RawMaterialWarehousingEntryEdit {
            get {
                return ResourceManager.GetString("RawMaterialWarehousingEntryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Warehousing Result.
        /// </summary>
        public static string RawMaterialWarehousingResult {
            get {
                return ResourceManager.GetString("RawMaterialWarehousingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Custom Handling Amount.
        /// </summary>
        public static string RegisterCustomHandlingAmount {
            get {
                return ResourceManager.GetString("RegisterCustomHandlingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Freight Amount.
        /// </summary>
        public static string RegisterFreightAmount {
            get {
                return ResourceManager.GetString("RegisterFreightAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Raw Material Purchase Amount.
        /// </summary>
        public static string RegisterRawMaterialPurchaseAmount {
            get {
                return ResourceManager.GetString("RegisterRawMaterialPurchaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Raw Material Traiff Amount.
        /// </summary>
        public static string RegisterRawMaterialTraiffAmount {
            get {
                return ResourceManager.GetString("RegisterRawMaterialTraiffAmount", resourceCulture);
            }
        }
    }
}
