//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RLayout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RLayout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.RLayout", typeof(RLayout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string ContentDelete {
            get {
                return ResourceManager.GetString("ContentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Successfull !.
        /// </summary>
        public static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no row selected..
        /// </summary>
        public static string ErrorNoRowSelect {
            get {
                return ResourceManager.GetString("ErrorNoRowSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value already in used..
        /// </summary>
        public static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string HelloUser {
            get {
                return ResourceManager.GetString("HelloUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Successfull !.
        /// </summary>
        public static string InsertMsg {
            get {
                return ResourceManager.GetString("InsertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid value..
        /// </summary>
        public static string InValidValue {
            get {
                return ResourceManager.GetString("InValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number..
        /// </summary>
        public static string IsNumber {
            get {
                return ResourceManager.GetString("IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is being used in.
        /// </summary>
        public static string IsUsed {
            get {
                return ResourceManager.GetString("IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are loging in !.
        /// </summary>
        public static string LogingInMessage {
            get {
                return ResourceManager.GetString("LogingInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {0} characters..
        /// </summary>
        public static string Maxlength {
            get {
                return ResourceManager.GetString("Maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value less than or equal to {0}..
        /// </summary>
        public static string MaxValue {
            get {
                return ResourceManager.GetString("MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no less than {0} characters..
        /// </summary>
        public static string Minlength {
            get {
                return ResourceManager.GetString("Minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found..
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no printer machine found..
        /// </summary>
        public static string NoPrinterMachineFound {
            get {
                return ResourceManager.GetString("NoPrinterMachineFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter this field.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - - - Please select - - -.
        /// </summary>
        public static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session time out, please login again !.
        /// </summary>
        public static string SessiontimeoutRespone {
            get {
                return ResourceManager.GetString("SessiontimeoutRespone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle menu.
        /// </summary>
        public static string Togglemenu {
            get {
                return ResourceManager.GetString("Togglemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successfull !.
        /// </summary>
        public static string UpdateMsg {
            get {
                return ResourceManager.GetString("UpdateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
