//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources.View.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.View.User.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User.
        /// </summary>
        public static string ChangeTitle {
            get {
                return ResourceManager.GetString("ChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMBINATION CODE.
        /// </summary>
        public static string COMBINATIONCODE {
            get {
                return ResourceManager.GetString("COMBINATIONCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userid already in used on other data !.
        /// </summary>
        public static string ErrorDeleteDataUsed {
            get {
                return ResourceManager.GetString("ErrorDeleteDataUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert User.
        /// </summary>
        public static string InsertTitle {
            get {
                return ResourceManager.GetString("InsertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a number..
        /// </summary>
        public static string IsNumber {
            get {
                return ResourceManager.GetString("IsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Master.
        /// </summary>
        public static string MasterTitle {
            get {
                return ResourceManager.GetString("MasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than {0} characters..
        /// </summary>
        public static string Maxlength {
            get {
                return ResourceManager.GetString("Maxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER DATE.
        /// </summary>
        public static string MBRGSDT {
            get {
                return ResourceManager.GetString("MBRGSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER TIME.
        /// </summary>
        public static string MBRGSTM {
            get {
                return ResourceManager.GetString("MBRGSTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF UPDATE.
        /// </summary>
        public static string MBUPDT {
            get {
                return ResourceManager.GetString("MBUPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TIME.
        /// </summary>
        public static string MBUPDTM {
            get {
                return ResourceManager.GetString("MBUPDTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string MBUSAD1 {
            get {
                return ResourceManager.GetString("MBUSAD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string MBUSAD2 {
            get {
                return ResourceManager.GetString("MBUSAD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDRESS.
        /// </summary>
        public static string MBUSAD3 {
            get {
                return ResourceManager.GetString("MBUSAD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER CODE.
        /// </summary>
        public static string MBUSRCD {
            get {
                return ResourceManager.GetString("MBUSRCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER NAME.
        /// </summary>
        public static string MBUSRNM {
            get {
                return ResourceManager.GetString("MBUSRNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER SHORT NAME.
        /// </summary>
        public static string MBUSSNM {
            get {
                return ResourceManager.GetString("MBUSSNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEL NO.
        /// </summary>
        public static string MBUSTEL {
            get {
                return ResourceManager.GetString("MBUSTEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WT CALCULATION.
        /// </summary>
        public static string MBWTCAL {
            get {
                return ResourceManager.GetString("MBWTCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no less than {0} characters..
        /// </summary>
        public static string Minlength {
            get {
                return ResourceManager.GetString("Minlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter user id ....
        /// </summary>
        public static string PlaceholderTextSearch {
            get {
                return ResourceManager.GetString("PlaceholderTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID already in used.
        /// </summary>
        public static string RemoteUserId {
            get {
                return ResourceManager.GetString("RemoteUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already in used.
        /// </summary>
        public static string RemoteUsername {
            get {
                return ResourceManager.GetString("RemoteUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter this field.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT OF WGT CODE.
        /// </summary>
        public static string UNITOFWGTCODE {
            get {
                return ResourceManager.GetString("UNITOFWGTCODE", resourceCulture);
            }
        }
    }
}
