//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionItemNoMaterial
    {
        public long Id { get; set; }
        public int RawMaterialId { get; set; }
        public string InspectionNo { get; set; }
        public string RawMaterialNo { get; set; }
        public double Quantity { get; set; }
        public double Weight { get; set; }
        public string StatusCode { get; set; }
    }
}
