//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV001
    {
        public string CADSTNC { get; set; }
        public Nullable<System.DateTime> CARGSDT { get; set; }
        public Nullable<System.DateTime> CAUPDT { get; set; }
        public string CADTCD { get; set; }
        public string CACTLM1 { get; set; }
        public string CAINVTP { get; set; }
        public string CAINVST { get; set; }
        public string CAINVNO { get; set; }
        public string CACMDCD { get; set; }
        public string CAUSRCD { get; set; }
        public string CACTRTP { get; set; }
        public string CADPSCD { get; set; }
        public string CASPTCD { get; set; }
        public string CAPURGD { get; set; }
        public string CALCTCD { get; set; }
        public string CASTSCD { get; set; }
        public string CARSNCD { get; set; }
        public string CASECCD { get; set; }
        public string CASCTNC { get; set; }
        public string CAIDCD { get; set; }
        public string CATRDCD { get; set; }
        public string CASPEC { get; set; }
        public string CACOAT { get; set; }
        public Nullable<double> CACOATF { get; set; }
        public Nullable<double> CACOATB { get; set; }
        public string CAGRADE { get; set; }
        public string CACMBT { get; set; }
        public string CACMBW { get; set; }
        public string CACMBL { get; set; }
        public Nullable<double> CASIZET { get; set; }
        public Nullable<double> CASIZEW { get; set; }
        public Nullable<double> CASIZEL { get; set; }
        public Nullable<double> CABSZT { get; set; }
        public Nullable<double> CABSZW { get; set; }
        public Nullable<double> CABSZL { get; set; }
        public Nullable<double> CACILID { get; set; }
        public Nullable<double> CACILOD { get; set; }
        public Nullable<double> CAQTY { get; set; }
        public Nullable<double> CAINPCK { get; set; }
        public Nullable<double> CAWT { get; set; }
        public string CAPRUPU { get; set; }
        public Nullable<double> CAPURUP { get; set; }
        public Nullable<double> CAPRUPD { get; set; }
        public Nullable<double> CADNSTY { get; set; }
        public string CACTRNO { get; set; }
        public Nullable<double> CACTITM { get; set; }
        public string CAMKCD { get; set; }
        public string CAORDNO { get; set; }
        public string CASPLCD { get; set; }
        public string CASPPNO { get; set; }
        public string CATCNO { get; set; }
        public string CAMCSPC { get; set; }
        public string CAVESEL { get; set; }
        public Nullable<int> CASMNTH { get; set; }
        public string CAPIVNO { get; set; }
        public Nullable<System.DateTime> CAPIVDT { get; set; }
        public string CAISPNO { get; set; }
        public Nullable<double> CACRLOS { get; set; }
        public Nullable<double> CAINDCT { get; set; }
        public Nullable<System.DateTime> CASEDT { get; set; }
        public Nullable<System.DateTime> CASHPDT { get; set; }
        public string CASTKPO { get; set; }
        public Nullable<System.DateTime> CAPODT { get; set; }
        public Nullable<System.DateTime> CAPAYDT { get; set; }
        public string CADCRCD { get; set; }
        public string CACRRCD { get; set; }
        public Nullable<double> CAEXRT { get; set; }
        public string CAEXRTT { get; set; }
        public Nullable<double> CATXEXR { get; set; }
        public string CATEXRT { get; set; }
        public string CATXCD { get; set; }
        public Nullable<double> CATXRT { get; set; }
        public string CAPSLP { get; set; }
        public Nullable<double> CAPSLPI { get; set; }
        public string CAPUFRT { get; set; }
        public string CAPFUPU { get; set; }
        public Nullable<double> CAPFRUP { get; set; }
        public string CACTPDT { get; set; }
        public string CACTUPU { get; set; }
        public Nullable<double> CACTUP { get; set; }
        public string CATRPDT { get; set; }
        public string CATRUPU { get; set; }
        public Nullable<double> CATRFUP { get; set; }
        public string CAOENO { get; set; }
        public Nullable<double> CAOEITM { get; set; }
        public string CACSTCD { get; set; }
        public Nullable<System.DateTime> CADLVDT { get; set; }
        public string CACTSPC { get; set; }
        public string CAOEPO { get; set; }
        public string CAPRDNM { get; set; }
        public string CAPCKTP { get; set; }
        public string CAUSMNG { get; set; }
        public Nullable<double> CASLUWT { get; set; }
        public Nullable<double> CAPCKWT { get; set; }
        public Nullable<double> CACALWT { get; set; }
        public string CAJOBNO { get; set; }
        public Nullable<double> CAJBITM { get; set; }
        public Nullable<System.DateTime> CAPRCDT { get; set; }
        public string CAPRCTP { get; set; }
        public string CAMCHNO { get; set; }
        public string CASUBNO { get; set; }
        public string CAOGLNO { get; set; }
        public Nullable<System.DateTime> CAISSDT { get; set; }
        public Nullable<System.DateTime> CAANNDT { get; set; }
        public string CADMGCD { get; set; }
        public string CAPCKNO { get; set; }
        public Nullable<System.DateTime> CAPCKDT { get; set; }
        public string CAPCKM { get; set; }
        public string CAADJNO { get; set; }
        public string CADINO { get; set; }
        public string CADONO { get; set; }
        public string CADLVTO { get; set; }
        public Nullable<System.DateTime> CADLDTT { get; set; }
        public Nullable<System.DateTime> CAIVCDT { get; set; }
        public string CASSLP { get; set; }
        public Nullable<double> CAISSLP { get; set; }
        public Nullable<double> CAPURAT { get; set; }
        public Nullable<double> CAPUFAT { get; set; }
        public Nullable<double> CAHCGAT { get; set; }
        public Nullable<double> CATRFAT { get; set; }
        public Nullable<double> CACSTHC { get; set; }
        public Nullable<double> CAYLDAT { get; set; }
        public Nullable<double> CAINTPC { get; set; }
        public Nullable<double> CAPRATB { get; set; }
        public Nullable<double> CAINTPK { get; set; }
        public Nullable<double> CAPKATB { get; set; }
        public long ID { get; set; }
    }
}
