//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA003
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MCRGSDT { get; set; }
        public string MCRGSTM { get; set; }
        public Nullable<System.DateTime> MCUPDT { get; set; }
        public string MCUPDTM { get; set; }
        public string MCIDCD { get; set; }
        public string MCIDNM { get; set; }
        public string MCSCTLV { get; set; }
        public string MCPASS { get; set; }
        public string MCSCTNC { get; set; }
    }
}
