//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA002
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MBRGSDT { get; set; }
        public string MBRGSTM { get; set; }
        public Nullable<System.DateTime> MBUPDT { get; set; }
        public string MBUPDTM { get; set; }
        public string MBUSRCD { get; set; }
        public string MBUSRNM { get; set; }
        public string MBUSSNM { get; set; }
        public string MBUSAD1 { get; set; }
        public string MBUSAD2 { get; set; }
        public string MBUSAD3 { get; set; }
        public string MBUSTEL { get; set; }
        public string MBWTCAL { get; set; }
        public Nullable<int> MBCOMCD { get; set; }
        public Nullable<int> MBUNICD { get; set; }
    }
}
