//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA004
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MDRGSDT { get; set; }
        public string MDRGSTM { get; set; }
        public Nullable<System.DateTime> MDUPDT { get; set; }
        public string MDUPDTM { get; set; }
        public string MDLCTCD { get; set; }
        public string MDWRCTG { get; set; }
        public string MDLCTNM { get; set; }
    }
}
