//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA001
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MARGSDT { get; set; }
        public string MARGSTM { get; set; }
        public Nullable<System.DateTime> MAUPDT { get; set; }
        public string MAUPDTM { get; set; }
        public string MASPCD { get; set; }
        public string MASPNM { get; set; }
        public string MASPSNM { get; set; }
        public string MASPAD1 { get; set; }
        public string MASPAD2 { get; set; }
        public string MASPAD3 { get; set; }
        public string MACNTRC { get; set; }
        public string MASPTEL { get; set; }
        public string MASPFAX { get; set; }
        public string MABUZCD { get; set; }
        public string MAIDCD { get; set; }
        public string MASPCTG { get; set; }
        public string MASTDUE { get; set; }
        public Nullable<decimal> MASCLSD { get; set; }
        public Nullable<decimal> MASDFER { get; set; }
        public Nullable<decimal> MASSETL { get; set; }
        public Nullable<decimal> MACLTRM { get; set; }
        public string MASDAYS { get; set; }
        public string MASCRCD { get; set; }
        public string MASTXCD { get; set; }
        public string MASCALC { get; set; }
        public string MAPTDUE { get; set; }
        public Nullable<decimal> MAPCLSD { get; set; }
        public Nullable<decimal> MAPDFER { get; set; }
        public Nullable<decimal> MAPSETEL { get; set; }
        public Nullable<decimal> MAPYTRM { get; set; }
        public string MAPDAYS { get; set; }
        public string MAPCRCD { get; set; }
        public string MAPTXCD { get; set; }
        public string MAPCALC { get; set; }
    }
}
