//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA009
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MJRGSDT { get; set; }
        public string MJRGSTM { get; set; }
        public Nullable<System.DateTime> MJUPDT { get; set; }
        public string MJUPDTM { get; set; }
        public string MJCRRCD { get; set; }
        public string MJEXRTT { get; set; }
        public Nullable<double> MJEXRTD { get; set; }
        public Nullable<double> MJEXRT { get; set; }
        public Nullable<double> MJTXEXR { get; set; }
    }
}
