//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA006
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MFRGSDT { get; set; }
        public string MFRGSTM { get; set; }
        public Nullable<System.DateTime> MFUPDT { get; set; }
        public string MFUPDTM { get; set; }
        public string MFPRDSP { get; set; }
        public Nullable<decimal> MFPNSTY { get; set; }
        public string MFRMK10 { get; set; }
        public string CMOCD { get; set; }
    }
}
