//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA010
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MKRGSDT { get; set; }
        public string MKRGSTM { get; set; }
        public Nullable<System.DateTime> MKUPDT { get; set; }
        public string MKUPDTM { get; set; }
        public string MKTXCD { get; set; }
        public string MKTXDL { get; set; }
        public Nullable<decimal> MKTXRT { get; set; }
        public Nullable<System.DateTime> MKFRDT { get; set; }
    }
}
