//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA011
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> MLRGSDT { get; set; }
        public string MLRGSTM { get; set; }
        public Nullable<System.DateTime> MLUPDT { get; set; }
        public string MLUPDTM { get; set; }
        public string MLCSTCD { get; set; }
        public string MLCRDRK { get; set; }
        public Nullable<decimal> MLVLDTR { get; set; }
        public Nullable<decimal> MLCRDLM { get; set; }
    }
}
