//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrinterSetting
    {
        public int ID { get; set; }
        public string PrinterName { get; set; }
        public string PaperName { get; set; }
        public Nullable<int> Copies { get; set; }
        public Nullable<byte> isHorizontal { get; set; }
        public Nullable<byte> Active { get; set; }
    }
}
