//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUH001
    {
        public string GFDSTNC { get; set; }
        public Nullable<System.DateTime> GFRGSDT { get; set; }
        public Nullable<System.DateTime> GFUPDT { get; set; }
        public Nullable<System.DateTime> GFTRNDT { get; set; }
        public string GFDTTYP { get; set; }
        public string GFJSLPN { get; set; }
        public Nullable<double> GFJSLPB { get; set; }
        public Nullable<double> GFIJSLP { get; set; }
        public Nullable<double> GFSBSLP { get; set; }
        public string GFSPCTG { get; set; }
        public string GFBKDIV { get; set; }
        public string GFDPSCD { get; set; }
        public Nullable<System.DateTime> GFBKDT { get; set; }
        public Nullable<System.DateTime> GFSEDT { get; set; }
        public Nullable<System.DateTime> GFIVCDT { get; set; }
        public string GFTRDCD { get; set; }
        public string GFCTRTP { get; set; }
        public string GFSPTCD { get; set; }
        public string GFSECCD { get; set; }
        public string GFCMDCD { get; set; }
        public string GFDFTSR { get; set; }
        public string GFRSNCD { get; set; }
        public string GFINVTP { get; set; }
        public string GFSTSCD { get; set; }
        public string GFSEQKY { get; set; }
        public string GFPRCTP { get; set; }
        public string GFMCHNO { get; set; }
        public string GFLCTCD { get; set; }
        public string GFDCRCD { get; set; }
        public string GFSPCD { get; set; }
        public string GFUSRCD { get; set; }
        public string GFIDCD { get; set; }
        public string GFIVCNO { get; set; }
        public Nullable<double> GFIVREV { get; set; }
        public string GFSPPNO { get; set; }
        public string GFPIVNO { get; set; }
        public Nullable<System.DateTime> GFPIVDT { get; set; }
        public string GFOENO { get; set; }
        public Nullable<double> GFOEITM { get; set; }
        public Nullable<System.DateTime> GFPYDUE { get; set; }
        public string GFPONO { get; set; }
        public string GFCTINF { get; set; }
        public string GFORDNO { get; set; }
        public string GFPRDSP { get; set; }
        public string GFSPEC { get; set; }
        public string GFGRADE { get; set; }
        public Nullable<double> GFSIZET { get; set; }
        public Nullable<double> GFSIZEW { get; set; }
        public Nullable<double> GFSIZEL { get; set; }
        public string GFPRDNM { get; set; }
        public string GFPCKTP { get; set; }
        public string GFCRRCD { get; set; }
        public string GFEXRTT { get; set; }
        public Nullable<double> GFEXRT { get; set; }
        public string GFTEXRT { get; set; }
        public Nullable<double> GFTXEXR { get; set; }
        public Nullable<double> GFQTY { get; set; }
        public Nullable<double> GFWT { get; set; }
        public string GFUPU { get; set; }
        public Nullable<double> GFUP { get; set; }
        public Nullable<double> GFAMT { get; set; }
        public Nullable<double> GFTXAT { get; set; }
        public Nullable<double> GFDAMT { get; set; }
        public Nullable<double> GFTXATD { get; set; }
        public Nullable<double> GFPURAT { get; set; }
        public Nullable<double> GFPUFAT { get; set; }
        public Nullable<double> GFHCGAT { get; set; }
        public Nullable<double> GFTRFAT { get; set; }
        public Nullable<double> GFCSTHC { get; set; }
        public Nullable<double> GFYLDAT { get; set; }
        public Nullable<double> GFINTPC { get; set; }
        public Nullable<double> GFPRATB { get; set; }
        public Nullable<double> GFINTPK { get; set; }
        public Nullable<double> GFPKATB { get; set; }
        public Nullable<double> GFPFTLS { get; set; }
        public long ID { get; set; }
    }
}
