//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUR001
    {
        public long ID { get; set; }
        public string AADSTNC { get; set; }
        public Nullable<System.DateTime> AARGSDT { get; set; }
        public Nullable<System.DateTime> AAUPDT { get; set; }
        public string AADTCD { get; set; }
        public string AAMKCD { get; set; }
        public string AAPURNO { get; set; }
        public Nullable<double> AACTITM { get; set; }
        public string AASPLCD { get; set; }
        public string AAUSRCD { get; set; }
        public string AASCTNC { get; set; }
        public string AAIDCD { get; set; }
        public string AACMDCD { get; set; }
        public string AATRDCD { get; set; }
        public string AACTRTP { get; set; }
        public string AADPSCD { get; set; }
        public string AASPTCD { get; set; }
        public string AASHPDT { get; set; }
        public string AASPPNO { get; set; }
        public string AATCNO { get; set; }
        public string AACRRCD { get; set; }
        public string AAEXRTT { get; set; }
        public Nullable<double> AAEXRT { get; set; }
        public string AATXCD { get; set; }
        public Nullable<double> AATXRT { get; set; }
        public string AATEXRT { get; set; }
        public Nullable<double> AATXEXR { get; set; }
        public string AACMPCD { get; set; }
        public Nullable<System.DateTime> AACMPDT { get; set; }
        public string AADLVCD { get; set; }
        public string AAUSMSG { get; set; }
        public string AACLLNO { get; set; }
        public string AASETRM { get; set; }
        public string AAPRICE { get; set; }
        public string AAPTTRM { get; set; }
        public string AADLPOT { get; set; }
        public string AARMK1 { get; set; }
        public string AARMK2 { get; set; }
        public string AARMK3 { get; set; }
        public string AARMK4 { get; set; }
        public string AARMK5 { get; set; }
        public string ABDSTNC { get; set; }
        public Nullable<System.DateTime> ABRGSDT { get; set; }
        public Nullable<System.DateTime> ABUPDT { get; set; }
        public string ABDTCD { get; set; }
        public string ABPURNO { get; set; }
        public Nullable<int> ABCTITM { get; set; }
        public string ABMCSPC { get; set; }
        public string ABCOAT { get; set; }
        public string ABGRADE { get; set; }
        public string ABCMBT { get; set; }
        public string ABCMBW { get; set; }
        public string ABCMBL { get; set; }
        public Nullable<double> ABSIZET { get; set; }
        public Nullable<double> ABSIZEW { get; set; }
        public Nullable<double> ABSIZEL { get; set; }
        public Nullable<double> ABBSZT { get; set; }
        public Nullable<double> ABBSZW { get; set; }
        public Nullable<double> ABBSZL { get; set; }
        public Nullable<System.DateTime> ABDLVDT { get; set; }
        public Nullable<double> ABQTY { get; set; }
        public Nullable<double> ABWT { get; set; }
        public Nullable<System.DateTime> ABSEDT { get; set; }
        public Nullable<double> ABTTLWT { get; set; }
        public Nullable<double> ABSESWT { get; set; }
        public string ABPRUPU { get; set; }
        public Nullable<double> ABPRUP { get; set; }
        public Nullable<double> ABPRUPD { get; set; }
        public Nullable<double> ABPRAT { get; set; }
        public Nullable<double> ABPRATD { get; set; }
        public Nullable<double> ABPTXAT { get; set; }
        public Nullable<double> ABPTXAD { get; set; }
        public string ABORDNO { get; set; }
        public Nullable<System.Guid> PURCODE { get; set; }
        public string AARMTP { get; set; }
        public string RAPSTLGR { get; set; }
        public string AAREVNO { get; set; }
        public string ABPRDNM { get; set; }
        public string ABPRDDIA { get; set; }
        public Nullable<byte> CompletetionStatus { get; set; }
    }
}
