//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterial
    {
        public int Id { get; set; }
        public string PurchaseContractNo { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public string ShippersInvoiceNo { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
        public string DepositAsset { get; set; }
        public string VesselName { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<System.DateTime> ShippersInvoiceDate { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
    }
}
