//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialType
    {
        public int Id { get; set; }
        public string RMTCD { get; set; }
        public string RMTNM { get; set; }
        public Nullable<System.DateTime> RMTGSDT { get; set; }
        public string RMTGSTM { get; set; }
        public Nullable<System.DateTime> RMTUPDT { get; set; }
        public string RMTUPTM { get; set; }
    }
}
