//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM0001
    {
        public Nullable<System.DateTime> SERGSDT { get; set; }
        public string SELCTCD { get; set; }
        public string SEINVNO { get; set; }
        public string SEISPNO { get; set; }
        public byte[] SEIDCD { get; set; }
        public long ID { get; set; }
        public string SEURID { get; set; }
    }
}
