//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Mapping_Action
    {
        public int Id { get; set; }
        public int PermissionRecord_Id { get; set; }
        public string CustomerRole_Id { get; set; }
        public int Action_Id { get; set; }
    }
}
