//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SteelGrade
    {
        public int Id { get; set; }
        public string Grade { get; set; }
        public string SAEsymbol { get; set; }
        public string C { get; set; }
        public string Mn { get; set; }
        public string P { get; set; }
        public string S { get; set; }
        public string Si { get; set; }
        public string Al { get; set; }
        public Nullable<System.DateTime> RGSDT { get; set; }
        public string RGSTM { get; set; }
        public Nullable<System.DateTime> UPDT { get; set; }
        public string UPTM { get; set; }
    }
}
