//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_MaterialWarehousingResult
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string Location_Code { get; set; }
        public string Inventory_No { get; set; }
        public string Inspection_No { get; set; }
        public int ID { get; set; }
    }
}
