//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopProSystem.Areas.MasterSetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA001
    {
        public long ID { get; set; }
        public string DADSTNC { get; set; }
        public Nullable<System.DateTime> DAUPDT { get; set; }
        public Nullable<System.DateTime> DATRNDT { get; set; }
        public string DAWSID { get; set; }
        public string DAPGMID { get; set; }
        public Nullable<System.DateTime> DALOGDT { get; set; }
        public string DALOGTP { get; set; }
        public string DAINVTP { get; set; }
        public string DAINVNO { get; set; }
        public string DACMDCD { get; set; }
        public string DAUSRCD { get; set; }
        public string DACTRTP { get; set; }
        public string DADPSCD { get; set; }
        public string DASPTCD { get; set; }
        public string DADFTSR { get; set; }
        public Nullable<double> DANORVS { get; set; }
        public string DABKCD { get; set; }
        public string DABKTMG { get; set; }
        public string DAPURGD { get; set; }
        public string DALCTCD { get; set; }
        public string DASTSCD { get; set; }
        public string DARSNCD { get; set; }
        public string DASECCD { get; set; }
        public string DASCTNC { get; set; }
        public string DAIDCD { get; set; }
        public string DACHGWK { get; set; }
        public string DATRDCD { get; set; }
        public string DASPEC { get; set; }
        public string DACOAT { get; set; }
        public string DAGRADE { get; set; }
        public Nullable<double> DABSZT { get; set; }
        public Nullable<double> DABSZW { get; set; }
        public Nullable<double> DABSZL { get; set; }
        public Nullable<double> DAQTY { get; set; }
        public Nullable<double> DAINPCK { get; set; }
        public string DAWTCD { get; set; }
        public Nullable<double> DAWT { get; set; }
        public string DAPUUPU { get; set; }
        public Nullable<double> DAPURUP { get; set; }
        public string DACTRNO { get; set; }
        public Nullable<double> DACTITM { get; set; }
        public string DAMKCD { get; set; }
        public string DAORDNO { get; set; }
        public string DASPLCD { get; set; }
        public string DASPPNO { get; set; }
        public string DATCNO { get; set; }
        public string DAVESEL { get; set; }
        public string DASMNTH { get; set; }
        public string DAPIVNO { get; set; }
        public Nullable<System.DateTime> DAPIVDT { get; set; }
        public string DAISPNO { get; set; }
        public Nullable<System.DateTime> DASEDT { get; set; }
        public Nullable<double> DAEXRT { get; set; }
        public string DAEXRTT { get; set; }
        public Nullable<double> DATXEXR { get; set; }
        public string DATEXRT { get; set; }
        public string DATXCD { get; set; }
        public Nullable<double> DATXRT { get; set; }
        public string DAPSLP { get; set; }
        public Nullable<double> DAPSLPI { get; set; }
        public string DAOPSLP { get; set; }
        public Nullable<double> DAIOPSL { get; set; }
        public string DAPUFRT { get; set; }
        public string DAPFUPU { get; set; }
        public Nullable<double> DAPFRUP { get; set; }
        public string DACTPDT { get; set; }
        public string DACTUPU { get; set; }
        public Nullable<double> DACTUP { get; set; }
        public string DATRPDT { get; set; }
        public string DATRUPU { get; set; }
        public Nullable<double> DATRFUP { get; set; }
        public string DAOENO { get; set; }
        public Nullable<double> DAOEITM { get; set; }
        public Nullable<System.DateTime> DAOEDT { get; set; }
        public string DACSTCD { get; set; }
        public string DACTSPC { get; set; }
        public string DAPONO { get; set; }
        public string DAPRDNM { get; set; }
        public string DACTINF { get; set; }
        public string DAPCKTP { get; set; }
        public string DASLUPU { get; set; }
        public Nullable<double> DASLUP { get; set; }
        public string DAUSMNG { get; set; }
        public string DAJOBNO { get; set; }
        public Nullable<double> DAJBITM { get; set; }
        public Nullable<System.DateTime> DAPRCDT { get; set; }
        public string DAPRCTP { get; set; }
        public string DAMCHNO { get; set; }
        public string DAOGLNO { get; set; }
        public string DASHIFT { get; set; }
        public Nullable<double> DABALWT { get; set; }
        public Nullable<double> DACALWT { get; set; }
        public string DAPCKNO { get; set; }
        public Nullable<System.DateTime> DAPCKDT { get; set; }
        public string DAPCKM { get; set; }
        public string DAADJNO { get; set; }
        public string DADINO { get; set; }
        public string DADONO { get; set; }
        public Nullable<double> DADOSUB { get; set; }
        public string DADLVTO { get; set; }
        public Nullable<System.DateTime> DADLDTT { get; set; }
        public Nullable<System.DateTime> DAIVCDT { get; set; }
        public string DASSLP { get; set; }
        public Nullable<double> DAISSLP { get; set; }
        public string DAOSSLP { get; set; }
        public Nullable<double> DAIOSSL { get; set; }
        public string DAFRPDT { get; set; }
        public string DAFRUPU { get; set; }
        public Nullable<double> DAFRTUP { get; set; }
        public string DATRUCK { get; set; }
        public string DARMK20 { get; set; }
        public string DAFHPDT { get; set; }
        public string DAUPUHF { get; set; }
        public Nullable<double> DAUPHFR { get; set; }
        public Nullable<double> DAPURAT { get; set; }
        public Nullable<decimal> DAPUFAT { get; set; }
        public Nullable<double> DAHCGAT { get; set; }
        public Nullable<decimal> DATRFAT { get; set; }
        public Nullable<decimal> DACSTHC { get; set; }
        public Nullable<double> DAYLDAT { get; set; }
        public Nullable<double> DAINTPC { get; set; }
        public Nullable<double> DAPRATB { get; set; }
        public Nullable<double> DAINTPK { get; set; }
        public Nullable<double> DAPKATB { get; set; }
        public Nullable<double> DAPRUP { get; set; }
        public Nullable<double> DAPRUPD { get; set; }
        public Nullable<double> DAPTXAT { get; set; }
        public Nullable<double> DAPTXAD { get; set; }
        public Nullable<double> DAPURATD { get; set; }
        public string DACRRCD { get; set; }
        public string DAMCSPC { get; set; }
        public string DAPRDDIA { get; set; }
        public string DASTLGR { get; set; }
        public Nullable<double> DAPTXATD { get; set; }
        public string DAUPDTM { get; set; }
    }
}
